var library = {
  url: {
      subdir: "", // /medicine
      doc_page: "https://www.doctoroncall.com.my",
      checkout:"/checkout/#!/shopping_cart",
      signup_login: "/patient#/signup",
      find_doctor: "/find-doctor",
      medicine: "/medicine/en",
      about_us: "/aboutUs",
      tanya: "/tanya/en",
      tanya_bm: "/tanya/",
      article: "/penyakit-a-z",
      soalan: "/soalan",
      faq: "#",
      media: "#",
      careers: "#",
      panel_doctors: "#",
      corporate_partnerships: "#",
      privacy_policy: "/privacyPolicy",
      terms_of_use: "/termsOfService",
      doctors_login: "/doctor#/signin",
      disp_poly: "/medicine/dispensation-policy",
      email: "mailto:contact@doctoroncall.com.my",
      tel_no: "tel:+60384082000",

      moh_email:"mailto:cprc@moh.gov.my",
      moh_no:"tel:+60388810200",

      doc_facebook: "https://www.facebook.com/doctoroncallMY/",
      doc_instagram: "https://www.instagram.com/doctoroncallmy/",
      doc_twitter: "https://twitter.com/doctoroncallmy",
      doc_whatsapp: "https://api.whatsapp.com/send?phone=60102721669&amp;text=DoctorOnCall 2019",
      footer_en_mens_health: "/mens-health",
      footer_en_womens_health: "/womens-health",
      footer_en_general_health: "/general-health",
      footer_en_sexual_health: "/sexual-health",
      footer_bm_mens_health: "/kesihatan-lelaki",
      footer_bm_womens_health: "/kesihatan-wanita",
      footer_bm_general_health: "/kesihatan",
      footer_bm_sexual_health: "/kesihatan-seksual",
      footer_hipertensi: "/hipertensi",
      footer_hipotensi: "/hipotensi",
      footer_hiv_aids: "/hiv-aids",
      footer_sinusitis: "/sinusitis",
      footer_menstruation: "/menstruasi",
      footer_buasir: "/buasir",
      footer_asma: "/asma",
      footer_diabetes: "/diabetes",
      footer_migrain: "/migrain",
      footer_klamidia: "/klamidia",
      footer_vaginosi_bakteria: "/vaginosis-bakteria",
      footer_vulvitis: "/vulvitis",
      footer_herpes_zoster: "/herpes-zoster",
      footer_HPV: "/HPV-human-papillomavirus",
      footer_kutu: "/kutu",
      footer_haid: "/haid-sakit",
      footer_viagra: "/sildenafil-ubat-viagra",
      footer_vaginitis: "/vaginitis",
      footer_prediabetes: "/prediabetes",
      footer_hipertensi_pulmonal: "/hipertensi-pulmonal",
      footer_disfungsi_seksual: "/disfungsi-seksual",
      footer_herpes_genital: "/herpes-genital-herpes-simplex",
      footer_kolestrol_tinggi: "/kolesterol-tinggi",
      footer_strok: "/penyebab-dan-gejala-stroke-angin-ahmar",
      footer_hepatitisB: "/penyebab-penyakit-hepatitis-b",
      footer_jenis1_diabetes: "/penyebab-dan-gejala-diabetes-jenis-1",
      footer_psoriasis: "/penyebab-dan-gejala-psoriasis",
      footer_gallstones: "/penyebab-dan-gejala-penyakit-gallstones-batu-karang-hempedu",
      footer_ejakulasi_pramatang: "/ejakulasi-pramatang-premature-ejaculation",
      footer_sifilis: "/penyebab-dan-gejala-sifilis-syphilis",
      footer_gonore: "/gonore-gonorrhea-gejala-penyebab-dan-rawatan",
      footer_hepatitsA: "/hepatitis-a-penyebab-dan-gejala",
      footer_jenis2_diabetes: "/diabetes-jenis-2-kencing-manis-penyebab-dan-gejala",
      footer_hepatitisC: "/hepatitis-c-penyebab-dan-gejala",
      footer_impotensi: "/impotensi-impotence-penyebab-dan-gejala",
      footer_diabetes_insipidus: "/diabetes-insipidus-penyebab-dan-gejala",
      footer_kandidiasis: "/penyakit-kandidiasis-candidiasis",
      footer_penyakit_kelamin: "/penyakit-kelamin-sti",
      footer_sakit_tekak: "/sakit-tekak-sore-throat",
      footer_ketuat: "/sakit-ketuat-wart",
      footer_tiroid: "/penyakit-tiroid-thyroid",
      footer_tonsil: "/sakit-tonsil-tonsilitis",
  },
  en: {
      cart_item_added:"Item added to cart",
      header_order_medicine: "Order Medicine",
      header_book_appointment: "Book Appointment",
      header_consult_doctor: "Consult A Doctor",
      header_more: "More",
      header_about_us: "About Us",
      header_ask_question: "Ask a Question",
      header_read_article: "Read Health Articles",
      header_faq: "FAQ",
      header_media: "Media",
      header_careers: "Careers",
      header_panel_doctors: "Panel Doctors",
      header_corporate_partnerships: "Corporate Partnerships",
      header_contact_us: "Contact Us",
      header_bm_eng: "BM / ENG",
      header_bm:"Bahasa",
      header_en:"English",
      header_button_signuplogin: "Sign Up / Login",
      footer_aboutdesc: "DoctorOnCall is Malaysia's first & largest online Doctor consultation platform that provides better healthcare services via chat, phone & video calls.",
      footer_button_readmore: "Read More",
      footer_services: "Our Services",
      footer_order_medicine: "Order Medicine",
      footer_consult_doctor: "Consult A Doctor",
      footer_ask_question: "Ask a Question",
      footer_read_article: "Read Health Articles",
      footer_search_hospitals: "Search Hospitals",
      footer_search_doctors: "Search Doctors",
      footer_book_appointment: "Book Appointment",
      footer_tanya_doktor: "Ask Doctor",
      footer_doctoroncall: "DoctorOnCall",
      footer_about_us: "About Us",
      footer_privacy: "Privacy",
      footer_faq: "FAQ",
      footer_contact_us: "Contact Us",
      footer_terms_of_use: "Terms of Use",
      footer_doctors_login: "Doctors Login",
      footer_media: "Media",
      footer_reach_us: "Contact Us",
      footer_social: "Social",
      footer_maps: "Site Map",
      footer_english: "English",
      footer_bahasa: "Bahasa",
      footer_health_centre: "Health Centre",
      footer_en_mens_health: "Men's Health",
      footer_en_womens_health: "Women's Health",
      footer_en_general_health: "General Health",
      footer_en_sexual_health: "Sexual Health",
      footer_bm_mens_health: "Kesihatan Lelaki",
      footer_bm_womens_health: "Kesihatan Wanita",
      footer_bm_general_health: "Kesihatan Umum",
      footer_bm_sexual_health: "Kesihatan Seksual",
      footer_hipertensi: "Hypertension",
      footer_hipotensi: "Hypotension",
      footer_hiv_aids: "HIV and AIDS",
      footer_sinusitis: "Sinusitis",
      footer_menstruation: "Menstruation",
      footer_buasir: "Hemorrhoids",
      footer_asma: "Asthma",
      footer_diabetes: "Diabetes",
      footer_migrain: "Migrain",
      footer_klamidia: "Chlamydia",
      footer_vaginosi_bakteria: "Bacterial vaginosis",
      footer_vulvitis: "Vulvitis",
      footer_herpes_zoster: "Herpes zoster",
      footer_HPV: "HPV",
      footer_kutu: "Lice",
      footer_haid: "Period pain",
      footer_viagra: "Viagra",
      footer_vaginitis: "Vaginitis",
      footer_prediabetes: "Prediabetes",
      footer_hipertensi_pulmonal: "Pulmonal hypertension",
      footer_disfungsi_seksual: "Sexual dysfunction",
      footer_herpes_genital: "Genital Herpes (Herpes Simplex)",
      footer_kolestrol_tinggi: "High cholestrol",
      footer_strok: "Stroke",
      footer_hepatitisB: "Hepatitis B",
      footer_jenis1_diabetes: "Type 1 Diabetes",
      footer_psoriasis: "Psoriasis",
      footer_gallstones: "Gallstones",
      footer_ejakulasi_pramatang: "Premature ejaculation",
      footer_sifilis: "Syphilis",
      footer_gonore: "Gonorrhea",
      footer_hepatitsA: "Hepatitis A",
      footer_jenis2_diabetes: "Type 2 Diabetes",
      footer_hepatitisC: "Hepatitis C",
      footer_impotensi: "Impotension",
      footer_diabetes_insipidus: "Diabetes insipidus",
      footer_kandidiasis: "Candidiasis - Introduction",
      footer_penyakit_kelamin: "Veneral disease - Introduction",
      footer_sakit_tekak: "Sore throat - single",
      footer_ketuat: "Warts",
      footer_tiroid: "Thyroid - Introduction",
      footer_tonsil: "Tonsilitis - Introduction",
      mainpage_shop_by_category: "Shop by Category",
      mainpage_medicine_drug: "Medicines and Prescription Drugs",
      mainpage_nutrition_vitamin_supplement: "Nutrition, Vitamins & Supplements",
      mainpage_personal_care: "Personal Care",
      mainpage_deliver_doorstep: "We deliver to your doorstep",
      mainpage_free_of_charge: "Free of charge",
      mainpage_order_now: "Online Pharmacy",
      mainpage_consult_doctor_now: "Find Doctor Now",
      mainpage_appointment_now: "Book Appointment Now",
      mainpage_read_health: "Read Health Articles Now",
      mainpage_ask_doctor_now: "Ask Doctor Now",
      category_quick_filter: "Quick Filter",
      product_advise: "It is advised to speak to a medical professional before consuming this product",
      product_img_disclaimer:"The product images shown are for illustration purposes only and may not be an exact representation of the product",
      product_prescription_required: "Prescription Required",
      product_discount: "-20%",
      product_RM: "RM ",
      product_out_of_stock: "Out of Stock",
      product_manufactured_by: "Manufactured by",
      product_supplied_buy: "Supplied by",
      product_active_ingredient: "Active Ingredient",
      product_packaging: "Packaging",
      product_quantity: "Quantity",
      product_add_to_cart: "Add To Cart",
      product_check_out: "Check Out",
      product_not_in_stock: "Not In Stock",
      product_about_medicine: "About Medicine",
      product_description_of: "Description of ",
      product_usage: "Usage",
      product_how_to_take: "How to take",
      product_dosage_composition: "Dosage & Composition",
      product_dosage_composition_of: "Dosage & Composition of ",
      product_professional_opinion: "Professional Opinion",
      product_professional_opinion_of: "Professional Opinion of ",
      product_precautionary_steps: "Precautionary Steps",
      product_precautionary_steps_of: "Precautionary Steps of ",
      product_side_effects: "Side Effects",
      product_side_effects_of: "Side Effects of ",
      product_frequently_ask_questions: "Frequently Asked Questions",
      product_frequently_ask_questions_of: "Frequently Asked Questions of ",
      product_information_updated: "Information last updated on: ",
      product_reviews:"Reviews (254)",
      product_disclaimer: "Disclaimer",
      product_disclaimer_desc: "The content provided on this webpage is to provide information only, to be fully-interpreted by a medical professional, and not intended as a guide to make purchase decisions, or a substitute to advice of a medical professional. Effectiveness and side effects of medication may differ from individual to individual. We do not encourage any customer to self-diagnose and/or self-medicate. Patients should always consult a medical professional before taking or using any medication. The content provided here is non-exhaustive and may not cover all aspects of the medication. Our service should only be used to support the doctor-patient dynamic, not replace it. <br><br>The fulfilment of prescription medication is subject to our review of a prescription issued by a Malaysian Medical Association (MMA) registered doctor. If required, we will provide a tele-consult service with one of our registered panel doctors. This is not an advertisement of a medicine as such an advertisement would require prior approval from the Medicines Advertisement Board of Malaysia.",
      product_available_area: "is available in many areas in Malaysia. Kuala Lumpur, Bukit Bintang, Titiwangsa, Setiawangsa, Wangsa Maju, Kepong, Segambut, Bandar Tun Razak, Cheras, Subang Jaya, Petaling Jaya, Mont Kiara, Puchong, Bandar Sunway, TTDI, Seri Kembangan, Klang, Bukit Tinggi, Damansara, Sentul, Penang, George Town, Jelutong, Gelugor, Bayan Baru, Bandar Baru Air Itam, Sungai Ara, Bukit Mertajam, Butterworth, Perai, Johor Bahru, Skudai, Bukit Indah, Gelang Patah, Senai, Pasir Gudang, Taman Daya, Taman Molek, Taman Perling, Tebrau, Danga Bay, Larkin, Nusajaya, Pontian, Masai, Setia Tropika, Desaru, Tampoi.",
      product_see_more: "See More",
      product_see_less: "See Less",
      product_unsure_medicine: "Unsure of your medicine?",
      product_get_help: "Get help from a certified doctor",
      product_consult_doctor: "Consult Doctor",
      product_see_all_review:"See All Reviews",
      product_related_health_article: "Related Health Articles",
      seo_product_title:"- Uses, Dosage, Side Effects,Price, Benefits - DoctorOnCall",
      seo_main_title:"Malaysia's Online Pharmacy | Order Medicine, Consult Doctor Online",
      seo_meta_desc:"Buy prescription & OTC medicines online on DoctorOnCall's pharmacy. Book appointment with doctors & hospitals, ask free health questions, consult specialist online. Get 20% off & free delivery on purchase of medicines",
      seo_meta_keyword: "Online Pharmacy, Buy precsription and OTC medicines, consult doctor online, book doctor appointments, ask free health questions",
      site_doctoroncall: "DoctorOnCall",
      mainpage_search_doc: "Search DoctorOnCall",
      mainpage_search_medicine: "Search Medicine",
      mainpage_searchsuggestion_glucose_control : "Glucose Control",
      mainpage_searchsuggestion_cholestrol_management: "Cholestrol Management",
      mainpage_searchsuggestion_blood_pressure: "Blood Pressure Control",
      mainpage_searchsuggestion_mens_condition: "Men's Condition",
      mainpage_searchsuggestion_birth_control: "Birth Control",
      mainpage_search_history: "Search History",
      mainpage_order_medication: "Order Medicine",
      mainpage_book_appointment: "Book Appointment",
      mainpage_consult_doctor: "Consult A Doctor",
      mainpage_ask_question: "Ask Free Question",
      mainpage_health_articles_days: "days ago",
      mainpage_health_articles_years : "yrs exp",
      mainpage_health_articles_gp: "General Practitioner",
      mainpage_pharma_order_medicine: "Order Medicine Online",
      mainpage_pharma_order_medicine_desc: "100% Genuine medicine, same day delivery. Private consultation with a registered doctor",
      mainpage_pharma_medicine: "Medicines",
      mainpage_pharma_wellness_lifestyle: "Wellness",
      mainpage_pharma_personal_care: "Personal Care",
      mainpage_pharma_lipitor_tablet: "Lipitor 20mg Tablet",
      mainpage_pharma_price_RM42: "RM 42.00",
      mainpage_pharma_add_to_cart: "Add to Cart",
      mainpage_pharma_crestor_tablet: "Crestor 10mg Tablet",
      mainpage_pharma_price_RM112: "RM 112.00",
      mainpage_plavix_tablet: "Plavix 75mg Tablet",
      mainpage_pharma_price_RM105: "RM 105.00",
      mainpage_pharma_norvasc_tablet: "Norvasc 5mg Tablet",
      mainpage_pharma_price_RM18: "RM 18.00",
      mainpage_pharma_aspirin: "Aspirin Cardio 100mg",
      mainpage_pharma_price_RM3_9: "RM 3.90 ",
      mainpage_pharma_flavette_tablet: "Flavettes Effervescent <br>Glow Tablet",
      mainpage_pharma_price_RM55: "RM 55.00",
      mainpage_pharma_rate_4_8: "(4.8)",
      mainpage_pharma_blackmore_vitamin: "Blackmores Buffered <br>Vitamin C",
      mainpage_pharma_rate_4_7: "(4.7)",
      mainpage_pharma_price_RM43_02: "RM 43.02",
      mainpage_pharma_neurobion: "Neurobion 10’s",
      mainpage_pharma_price_RM13_8: "RM 13.80",
      mainpage_pharma_berocca_tablet: "Berocca Effervescent <br>Tablet",
      mainpage_pharma_price_RM61_6: "RM 61.60",
      mainpage_pharma_blackmore_mineral_tablet: "Blackmores Multivitamins <br>+ Minerals Tablet",
      mainpage_pharma_price_RM32_8: "RM 32.80",
      mainpage_pharma_alpecin_shampoo: "Alpecin Caffeine Hybrid Shampoo",
      mainpage_pharma_price_RM34: "RM 34.00",
      mainpage_pharma_audace_tonic: "Audace Hair Tonic",
      mainpage_pharma_rate_4_5: "(4.5)",
      mainpage_pharma_price_RM47_92: "RM 47.92",
      mainpage_pharma_ripded_lotion: "Ridped Lotion",
      mainpage_pharma_rate_4_4: "(4.4)",
      mainpage_pharma_price_RM12: "RM 12.00",
      mainpage_pharma_selsun_suspension: "Selsun 2.5% Suspension",
      mainpage_pharma_price_RM43_70: "RM 43.70",
      mainpage_pharma_pantene_shampoo: "Pantene Hair Fall Shampoo",
      mainpage_pharma_price_RM15_90: "RM 15.90",
      mainpage_consult_doctor_online: "Consult Doctor Online",
      mainpage_consult_doctor_desc: "Connect to Malaysian Medical Council registered doctors and get the care you need in 3 simple steps",
      mainpage_consultdoc_step1: "1",
      mainpage_consultdoc_signup: "Sign up</a> or Log In <br> to DoctorOnCall",
      mainpage_consultdoc_step2: "2",
      mainpage_consultdoc_speak_with_doc: "Speak with a doctor and receive<br> treatment and answers",
      mainpage_consultdoc_step3: "3",
      mainpage_consultdoc_receive_med: "Receive your medication- <br> delivered to your doorstep!",
      mainpage_book_doctor_appointment: "Book Doctor Appointment",
      mainpage_book_doctor_appointment_desc: "Book your medical specialist appointment across Malaysia's trusted clinic & hospital chains",
      mainpage_bookdoc_pediatrician: "Pediatrician",
      mainpage_bookdoc_orthopaedic: "Orthopaedic",
      mainpage_bookdoc_obstetrician_gynecologist: "Obstetrician & Gynecologist",
      mainpage_bookdoc_cardiologist: "Cardiologist",
      mainpage_bookdoc_ear_nose_throat_specialist: "Ear Nose Throat Specialist",
      mainpage_bookdoc_dermatologist: "Dermatologist",
      mainpage_health_article: "Health Articles",
      mainpage_health_article_desc: "Expand your health knowledge immediately with answers from registered doctors",
      mainpage_category_general_health: "General Health",
      mainpage_category_mens_health: "Men's Health",
      mainpage_category_womens_health: "Women's Health",
      mainpage_category_sexual_health: "Sexual Health",
      mainpage_category_eye_condition: "Eye Condition",
      mainpage_category_sore_throat: "Sore Throat",
      mainpage_category_migraine: "Migraine",
      mainpage_category_minor_injury: "Minor Injuries",
      mainpage_category_fatty_liver: "Fatty Liver",
      mainpage_category_cough_cold: "Cough & Cold",
      mainpage_category_dengue: "Dengue",
      mainpage_category_constipation: "Constipation",
      mainpage_category_skin_condition: "Skin Condition",
      mainpage_category_asthma: "Asthma",
      mainpage_category_acid_reflux: "Acid Reflux",
      mainpage_category_erectile_dysfunction: "Erectile Dysfunction",
      mainpage_category_premature_ejaculation: "Premature Ejaculation",
      mainpage_category_vaginal_discharge: "Vaginal Discharge",
      mainpage_category_missed_period: "Missed Period",
      mainpage_category_uti: "UTI",
      mainpage_category_irregular_period: "Irregular Period",
      mainpage_category_birth_control: "Birth Control",
      mainpage_category_syphilis: "Syphilis",
      mainpage_category_hiv: "HIV",
      mainpage_category_herpes: "Herpes",
      mainpage_category_gonorrhea: "Gonorrhea",
      mainpage_ask_doctor: "Ask Doctors",
      mainpage_ask_doctor_desc: "Ask your health questions anonymously and get answers from a qualified doctor within minutes",
      mainpage_askdoc_kencing_manis: "Kencing Manis",
      mainpage_askdoc_kencing_manis_question: "Sometimes I feel my tummy keeps on contracting once in a while but I can still feel the baby’s movement. Should I visit my doctor?",
      mainpage_askdoc_dr_sashini: "Dr Sashini",
      mainpage_askdoc_general_practitioner: "General Practitioner",
      mainpage_askdoc_mati_pucuk: "Mati Pucuk",
      mainpage_askdoc_mati_pucuk_question: "Bagaimana Slidenafil Ubat Viagra<br> Berkesan Dan Cara Pengunaan",
      mainpage_askdoc_keputihan: "Keputihan",
      mainpage_askdoc_keputihan_desc: "Penyebab, Diagnosis, Pengubatan Dan Pencegahan Penyakit Keputihan",
      mainpage_askdoc_vaginosis: "Vaginosis",
      mainpage_askdoc_vaginosis_question: "Apakah penyakit Vaginosis bakteria dan rawatannya?",
      mainpage_askdoc_urti: "URTI",
      mainpage_askdoc_urti_question: "Apakah URTI Dan Cara Mengelakkan Jangkitan?",
      mainpage_askdoc_haid_sakit: "Haid Sakit",
      mainpage_askdoc_haid_sakit_question: "Apakah senggugut dan bagaimana mencegah dan merawat?",
      mainpage_askdoc_vulvitis: "Vulvitis",
      mainpage_askdoc_vulvitis_question: "Apakah penyakit Vulvitis dan rawatan sesuai?",
      mainpage_askdoc_penyakit_kelamin: "Penyakit Kelamin",
      mainpage_askdoc_penyakit_kelamin_question: "Penyebab, Gejala, Diagnosis Dan Ubat Sesuai Untuk Penyakit Kelamin",
      mainpage_next_page: "Next Page",
      mainpage_connect_doctor_instant: "Connect With A Doctor Instantly",
      mainpage_connect_doctor_desc: "Call, chat or have a video call privately with a MMC registered doctor",
      mainpage_connect_doctor: "Connect With A Doctor",
      mainpage_featured_on: "Featured On",
      mainpage_subscribe_health_insight: "Subscribe to our Free Health Insights",
      mainpage_subscribe_desc: "Get notified about new health articles, and any new offers and new promotions. You can unsubscribe at any time. ",
      mainpage_subscribe: "Subscribe",
      tanya: "/tanya/en",


      stats_overview_text:"Stats Overview",
      stats_overview_confirmed_text:"Confirmed",
      stats_overview_recovered_text:"Recovered",
      stats_overview_death_text:"Death",
      stats_update:"Last Update",
      continue_website:"Continue to Website",
      consult_with_the:"Consult with the",
      moh_text:"Ministry of Health",
      tweet_from_moh:"Tweets from Official MOH Site",

      load_more_content_corona:"Load More",
      see_less_content_corona:"See Less",
      read_more_corona:"Read More",
      novel_corona_virus:"Novel Coronavirus",
      novel_corona_virus_desc:"WHO has been working with Chinese authorities and global experts from the day we were informed, to learn more about the virus, how it affects the people who are sick with it, how they can be treated, and what countries can do to respond.",
      ihr_corona_virus_text:"IHR Emergency Committee to reconvene on novel coronavirus in China",
      who_corona_virus_text:"WHO, China leaders discuss next steps in battle against coronavirus outbreak",
      missionsummary_corona_virus_text:"Mission summary: WHO Field Visit to Wuhan, China 20-21 January 2020",
      corona_consult_doc:"Consult A Doctor Now",
      corona_consult_doc_desc:"Worried about any symptoms you might have right now? Consult a doctor to know more.",
      consult_doc_btn_corona:"Consult A Doctor",
      try_answer_qustion_coronavirus:"We will try to answer your question",
      try_answer_qustion_subtext:"We have doctors ready to answer your questions for free.",
      what_is_novel_corona:"What is the 2019 Novel Coronavirus?",
      novel_corona_definition:"2019 Novel Coronavirus is a new type of respiratory virus from the coronavirus family which was first identified in Wuhan, Hubei Province, China.",
      ask_question_btn_corona:"Ask Your Question",
      no_panic_corona:"No Need To Panic.",
      list_frequently_question:"We list out for you the most frequently asked questions about Novel Coronavirus.",
      think_nov_virus_text:"Think you know all about Novel CoronaVirus (nCoV)?",
      take_quiz_btn:"Take A Quiz To Find Out!",
      why_call_corona:"Why is it called Novel Coronavirus?",
      why_call_corona_answer:"Novel means new and Novel Coronavirus means a new type of coronavirus that has not been identified previously.",
      where_come_from_corona:"Where does it come from?",
      where_come_from_corona_answer:"It is believed from the sample taken from the infected patients, the virus traced back to the local exotic market in Wuhan, Hubei Province, China.",
      how_infect_human:"How does the virus infect humans?",
      how_infect_human_answer:"The virus does infect from human-to-human although originally it may infect from animal-to-human. The mode of transmission is still unclear but as with other respiratory viruses, it may infect through water droplets (from sneezing or coughing).",
      can_virus_transmit:"Can the virus transmit from human to human?",
      can_virus_transmit_answer:"Yes it can.",
      how_long_incubation:"How long is the incubation period?",
      how_long_incubation_answer:"Incubation period is the period when a person first contacted with the infection to when the first symptom appears. It is thought that the Novel Coronavirus 2019 incubation period is 14 days. It means, an infected person may not show any symptom up to 14 days",



      corona_faq_7_title:"Is it infectious during the incubation period?",
    corona_faq_7_desc:"It is not known whether the virus can infect during incubation period or not. Researchers believed it can be due to how quick it spread across the globe. However, since this virus is still new, no conclusion can be given at this moment regarding its ability to infect during incubation period.",
    corona_faq_8_title:"Is this virus the same as MERs-Cov or SARS virus?",
    corona_faq_8_desc:"No it is not the same. However, 2019 Novel Coronavirus belongs to the same family which causes MERs-Cov and SARS outbreak, that is coronavirus.",
    corona_faq_9_title:"Is it the same as the influenza virus?",
    corona_faq_9_desc:"No. Influenza virus and coronavirus are not the same and totally belong to entirely different virus families despite some similarities with the symptoms.",
    corona_faq_10_title:"How do I protect myself from being infected by this virus?",
    corona_faq_10_desc:"These are the guidelines from Centre of Disease Control (CDC):<ul><li>MWash your hands often with soap and water for at least 20 seconds. Use an alcohol-based hand sanitizer that contains at least 60% alcohol if soap and water are not available.</li><li>Avoid touching your eyes, nose, and mouth with unwashed hands.</li><li>Avoid close contact with people who are sick.</li><li>Stay home when you are sick.</li><li>Cover your cough or sneeze with a tissue, then throw the tissue in the trash.</li><li>Clean and disinfect frequently touched objects and surfaces</li></ul>",



    corona_faq_11_title:"Can I get vaccinated against the 2019 Novel Coronavirus?",
    corona_faq_11_desc:"So far there is no vaccine that is able to prevent a person from getting infected with this virus.",
    corona_faq_12_title:"Is this virus derived from a vaccine?",
    corona_faq_12_desc:"No. The virus is thought to be evolving from coronavirus that infected wild animals and later infects humans.",
    corona_faq_13_title:"Does facemask protect me from this virus?",
    corona_faq_13_desc:"Facemask is not 100% proven to protect you against 2019 Coronavirus but it does lower your risk of getting it provided if other preventive measures are also taken.",
    corona_faq_14_title:"Which mask should I use to protect myself?",
    corona_faq_14_desc:"You can use the 3 or 2 layered surgical masks that are easily and cheap to find in many convenient stores and pharmacies. You may also use the N95 mask that can be repeatedly used compared to the surgical mask.",
    corona_faq_15_title:"What should I do if I had close contact with someone who got infected by this virus?",
    corona_faq_15_desc:"You should monitor closely your health for any signs of symptoms such as fever, coughing, shortness of breath and others up to 14 days. If you have any of the symptoms, please report to your healthcare provider immediately.",
    // Symptoms of Coronavirus
    corona_faq_16_title:"What are the symptoms of an infected person?",
    corona_faq_16_desc:"Symptoms of infected persons are such as:<ol><li>Fever</li><li>Coughing</li><li>Shortness of breath</li><li>Body ache</li><li>Sore throat</li><li>Headache</li><li>Runny nose</li></ol>",
    corona_faq_17_title:"How long does it take for symptoms to appear?",
    corona_faq_17_desc:"It can take up to 14 days before the first symptom can appear.",
    corona_faq_18_title:"What should I do if I have symptoms?",
    corona_faq_18_desc:"You should report to the nearest healthcare provider and make sure you note them as well of those who are confirmed or being evaluated for the 2019 Novel Coronavirus. You are also advised to avoid any place with crowds and from going to work or school.",
    corona_faq_19_title:"What are the complications that can occur if someone is infected by 2019 Coronavirus?",
    corona_faq_19_desc:"Serious complications include pneumonia, respiratory failure, septic shock and even death.",
    // Diagnosis of Coronavirus
    corona_faq_20_title:"How do you test a person for the 2019 Coronavirus?",
    corona_faq_20_desc:"High risk people will be tested with their blood taken and sent for viral genetic confirmation called Polymerase Chain Reaction (PCR) for confirmation.",


    corona_faq_21_title:"Should I get tested?",
    corona_faq_21_desc:"The decision of whether a person needs to be checked is depending on the doctor's evaluation of the patient's history and risks. If a person develops symptoms such as fever and respiratory symptoms and has close contact or travelled from/to Wuhan, China in the last 14 days, he/she will be further evaluated for diagnostic testing.",
    corona_faq_22_title:"How can I get tested for the 2019 Novel Coronavirus?",
    corona_faq_22_desc:"The decision of whether a person needs to be checked is depending on the doctor's evaluation of the patient's history and risks. If a person develops symptoms such as fever and respiratory symptoms and has close contact or travelled from/to Wuhan, China in the last 14 days, he/she will be further evaluated for diagnostic testing.",
    // Travel Safety
    corona_faq_23_title:"Is it safe to travel to China?",
    corona_faq_23_desc:"The situation is still evolving and as the World Health Organisation (WHO) issued, the number of cases and death are still on the rise in China and thus CDC has advised to avoid any non-essential travel to China at the moment.",
    corona_faq_24_title:"Is it safe to travel to other countries?",
    corona_faq_24_desc:"Travelling to other countries other than China is still considered safe despite the risk of this disease to spread globally as strict measures are taken by every country to minimise the risk.",
    corona_faq_25_title:"Can my child go to school?",
    corona_faq_25_desc:"Your child can go to school as usual unless he/she develops one of the symptoms and has had contact with suspected or confirmed patients of this virus. Follow closely with the school in case it needs to be closed down for the outbreak reason.",
    corona_faq_26_title:"I recently travelled to China and got sick after I came back. What should I do?",
    corona_faq_26_desc:"You should report and go to your nearest healthcare provider as soon as possible. Delaying in presenting yourself may bring more harm.",
    corona_faq_27_title:"Should I quarantine myself if I just got back from China?",
    corona_faq_27_desc:"You are advised to closely monitor for any signs of the symptoms within 14 days while taking strict preventive measure per CDC or MOH guidelines. Avoid going to crowded places until you are definitely sure there are no symptoms after 14 days.",
    //  Soalan Lain Tentang Wabak Coronavirus 
    corona_faq_28_title:"What is the risk of getting infected from parcels or products received from China?",
    corona_faq_28_desc:"Since 2019 Coronavirus is more similar to SARS virus, it is not entirely sure if it can spread or infects people receiving parcels or products from China. It is thought that the chances of this to happen is very low since the survival of the virus is limited outside its host at ambient temperature.",
    corona_faq_29_title:"Is it safe to consume animal or animal products imported from China?",
    corona_faq_29_desc:"There is no evidence so far to suggest the risk of getting infected from the animal or its products imported from China. Since the risk is still on the rise, it is better to take safe precautions and avoid any unnecessary animal products imported from China.",
    corona_faq_30_title:"Can pets or animals transmit 2019 Novel Coronavirus?",
    corona_faq_30_desc:"The first few cases of 2019 Coronavirus may have transmitted from animal to human but now it is from human-to-human transmission. There is no evidence or reason to suggest pets to transmit the virus.",
    
    
    corona_faq_31_title:"Can animals get infected from human?",
    corona_faq_31_desc:"The 2019 Coronavirus is not known to infect animals or not but the risk is still there as the virus can transmit from animal-to-human.",
    corona_faq_32_title:"How deadly is the virus?",
    corona_faq_32_desc:"The virus can cause mild symptoms to severe complications such as respiratory failure and even death.",
    corona_faq_33_title:"Is there a treatment or cure for this virus?",
    corona_faq_33_desc:"The 2019 Coronavirus is currently being treated with the same medications used on HIV patients in China.",
    corona_faq_34_title:"How many deaths has been caused by this virus?",
    corona_faq_34_desc:"As up to 30/01/2020, the official death figure released by WHO is at 170 people.",
    corona_faq_35_title:"Does infection by this virus means death?",
    corona_faq_35_desc:"It does not necessarily cause death to people as currently there are more than 8000 positive infected people but only 170 deaths recorded so far.",
    corona_faq_36_title:"Who is at risk?",
    corona_faq_36_desc:"Children, old people, pregnant women, cancer and chronic illness patients, people with long-term respiratory illness and people travelling to China or with close contact with suspected/confirmed patients.",
    corona_faq_37_title:"Can it infect healthy people?",
    corona_faq_37_desc:"Yes it can.",
    corona_faq_38_title:"Should I avoid certain food?",
    corona_faq_38_desc:"Eat a healthy and balanced diet and avoid exotic food or imported food and food from dirty restaurants/stalls.",
    corona_faq_39_title:"Should I avoid consuming food imported from China?",
    corona_faq_39_desc:"There is no evidence to suggest all food imported from China poses risk of transmitting the virus. As for now, it is better to consume locally produced food.",      
    corona_faq_40_title:"Does taking vitamin C help?",
    corona_faq_40_desc:"There is no evidence to suggest the role of vitamin C in fighting off the infection.",

    
    corona_faq_41_title:"What kind of supplement should I take?",
    corona_faq_41_desc:"There are no supplements or products advisable for people to take regarding this outbreak as there is no evidence to support any of the supplements or products sold out there.",
    corona_faq_42_title:"How bad is the situation of this infection in Malaysia?",
    corona_faq_42_desc:"Currently there are only 7 positive cases recorded but no death regarding this infection here in Malaysia so far.",
    corona_faq_43_title:"How can I assess myself from home before visiting the hospital if I am unwell?",
    corona_faq_43_desc:"You can use a home thermometer and if you have one of the symptoms plus with close contact with people from China or have recently travelled from/to China in the last 14 days, you should seek immediate medical help.",
    corona_faq_44_title:"Which hospitals can I go to if I feel unwell?",
    corona_faq_44_desc:"You can go to any government or private hospital if you are feeling unwell.",
    corona_faq_45_title:"Can I collect my own phlegm to be sent for testing?",
    corona_faq_45_desc:"It is not advisable for you to collect your own phlegm as this may cause contamination and thus inaccuracy. If you are suspected of having the infection, doctors at the hospital will do all the investigation and assessment on you.",
    corona_faq_46_title:"If you cook an infected animal, can it kill the virus?",
    corona_faq_46_desc:"It is not known if this virus can be killed when the animal is being cooked. People should avoid exotic and infected animals even if they are being cooked.",
    corona_faq_47_title:"Can I still travel to China or Hong Kong?",
    corona_faq_47_desc:"The CDC has issued advice to avoid visiting China at the moment. Countries with high prevalence also should be avoided if there is no necessity.",
    corona_faq_48_title:"Can antibiotics kill this virus?",
    corona_faq_48_desc:"Antibiotics cannot kill any viruses including the 2019 Coronavirus.",
    corona_faq_49_title:"What is the role of DoctorOnCall during this outbreak?",
    corona_faq_49_desc:"DoctorOnCall is collaborating with the Minister of Health (MOH) to spread correct, factual and uptodate information regarding the 2019 Coronavirus to the public.",
    corona_faq_50_title:"Where can I find more information or updates about 2019 Coronavirus?",
    corona_faq_50_desc:"You can visit the MOH official websites/portal or the Public Health Malaysia Facebook page as well as follow us at www.doctoroncall.com.my/coronavirus for further concise and accurate information on this matter."

  },



  bm: {
      cart_item_added:"Dimasukan ke Troli", //TODO - translate
      header_order_medicine: "Beli Ubat",
      header_book_appointment: "Buat Temu Janji",
      header_consult_doctor: "Konsultasi bersama Doktor",
      header_more: "Lebih Lanjut",
      header_about_us: "Tentang Kami",
      header_ask_question: "Tanya Soalan",
      header_read_article: "Baca Artikel Kesihatan",
      header_faq: "FAQ",
      header_media: "Media",
      header_careers: "Kerjaya",
      header_panel_doctors: "Panel Doktor",
      header_corporate_partnerships: "Rakan Kongsi Korporat",
      header_contact_us: "Hubungi Kami",
      header_bm_eng: "BM / ENG",
      header_bm:"Bahasa",
      header_en:"English",
      header_button_signuplogin: "Daftar / Log Masuk",
      footer_aboutdesc: "DoctorOnCall adalah platform konsultasi Doktor atas talian pertama & terbesar di Malaysia. Kami menyediakan perkhidmatan kesihatan melalui servis mesej, panggilan video & panggilan telefon.",
      footer_button_readmore: "Baca Lebih Lanjut ",
      footer_services: "Perkhidmatan Kami",
      footer_order_medicine: "Beli Ubat",
      footer_consult_doctor: "Konsultasi bersama Doktor",
      footer_ask_question: "Tanya Soalan",
      footer_read_article: "Baca Artikel Kesihatan",
      footer_search_hospitals: "Cari Hospital",
      footer_search_doctors: "Cari Doktor",
      footer_book_appointment: "Buat Temu Janji",
      footer_tanya_doktor: "Tanya Doktor (Soalan)",
      footer_doctoroncall: "DoctorOnCall",
      footer_about_us: "Tentang Kami",
      footer_privacy: "Privasi",
      footer_faq: "FAQ",
      footer_contact_us: "Hubungi Kami",
      footer_terms_of_use: "Terma Penggunaan",
      footer_doctors_login: "Log Masuk Doktor",
      footer_media: "Media",
      footer_reach_us: "Hubungi Kami",
      footer_social: "Sosial",
      footer_maps: "Peta",
      footer_english: "English",
      footer_bahasa: "Bahasa",
      footer_health_centre: "Pusat Kesihatan",
      footer_en_mens_health: "Men's Health",
      footer_en_womens_health: "Women's Health",
      footer_en_general_health: "General Health",
      footer_en_sexual_health: "Sexual Health",
      footer_bm_mens_health: "Kesihatan Lelaki",
      footer_bm_womens_health: "Kesihatan Wanita",
      footer_bm_general_health: "Kesihatan Umum",
      footer_bm_sexual_health: "Kesihatan Seksual",
      footer_hipertensi: "Hipertensi",
      footer_hipotensi: "Hipotensi",
      footer_hiv_aids: "HIV dan AIDS",
      footer_sinusitis: "Sinusitis",
      footer_menstruasi: "Menstruasi",
      footer_buasir: "Buasir",
      footer_asma: "Asma",
      footer_diabetes: "Diabetes",
      footer_migrain: "Migrain",
      footer_klamidia: "Klamidia",
      footer_vaginosis_bakteria: "Vaginosis bakteria",
      footer_vulvitis: "Vulvitis",
      footer_herpes_zoster: "Herpes zoster",
      footer_HPV: "HPV",
      footer_kutu: "Kutu",
      footer_haid_: "Haid-sakit",
      footer_viagra: "Viagra",
      footer_vaginitis: "Vaginitis",
      footer_prediabetes: "Prediabetes",
      footer_hipertensi_pulmonal: "Hypertensi pulmonal",
      footer_disfungsi_seksual: "Disfungsi seksual",
      footer_herpes_genital: "Herpes genital (herpes simplex)",
      footer_kolestrol_tinggi: "Kolestrol tinggi",
      footer_strok: "Strok",
      footer_hepatitisB: "Hepatitis B",
      footer_jenis1_diabetes: "Jenis 1 Diabetes",
      footer_psoriasis: "Psoriasis",
      footer_gallstones: "Gallstones",
      footer_ejakulasi_pramatang: "Ejakulasi pramatang",
      footer_sifilis: "Sifilis",
      footer_gonore: "Gonore",
      footer_hepatitsA: "Hepatitis A",
      footer_jenis2_diabetes: "Diabetes Jenis 2",
      footer_hepatitisC: "Hepatitis C",
      footer_impotensi: "Impotensi",
      footer_diabetes_insipidus: "Diabetes insipidus",
      footer_kandidiasis: "Kandidiasis - Pengenalan",
      footer_penyakit_kelamin: "Penyakit Kelamin - Pengenalan",
      footer_sakit_tekak: "Sakit tekak - single",
      footer_ketuat: "Ketuat",
      footer_tiroid: "Tiroid - Pengenalan",
      footer_tonsil: "Tonsil - pengenalan",
      mainpage_shop_by_category: "Beli Mengikut Kategori",
      mainpage_medicine_drug: "Ubat dan Preskripsi Ubat",
      mainpage_nutrition_vitamin_supplement: "Nutrisi, Vitamin & Suplemen",
      mainpage_personal_care: "Peribadi",
      mainpage_deliver_doorstep: "Kami menghantar sehingga ke pintu rumah anda",
      mainpage_free_of_charge: "Secara Percuma",
      mainpage_order_now: "Dapatkan Ubat Segera",
      mainpage_consult_doctor_now: "Hubungi Doktor Sekarang",
      mainpage_appointment_now: "Atur Temujanji Sekarang",
      mainpage_read_health: "Baca Artikel Kesihatan Sekarang",
      mainpage_ask_doctor_now: "Tanya Doktor Sekarang",
      category_quick_filter: "Tapisan Ringkas",
      product_advise: "Anda dinasihatkan untuk berunding dengan pakar perubatan sebelum mengambil produk ini",
      product_img_disclaimer:"The product images shown are for illustration purposes only and may not be an exact representation of the product",     //TODO: translate
      product_prescription_required: "Preskripsi Diperlukan",
      product_discount: "-20%",
      product_RM: "RM ",
      product_out_of_stock: "Kehabisan Stok",
      product_manufactured_by: "Dikilangkan oleh",
      product_supplied_buy: "Dibekalkan oleh",
      product_active_ingredient: "Bahan Aktif",
      product_packaging: "Pembungkusan",
      product_quantity: "Kuantiti",
      product_add_to_cart: "Masukkan ke Troli",
      product_check_out: "Semak Keluar", // Check Out // Still not sure //TODO
      product_not_in_stock: "Tiada Dalam Stok",
      product_about_medicine: "Tentang Ubat",
      product_description_of: "Penerangan tentang ",
      product_reviews:"Ulasan (254)",
      product_usage: "Penggunaan",
      product_how_to_take: "Cara Pengambilan",
      product_dosage_composition: "Sukatan dan Komposisi",
      product_dosage_composition_of: "Sukatan dan Komposisi untuk ",
      product_professional_opinion: "Nasihat Pakar",
      product_professional_opinion_of: "Nasihat Pakar mengenai ",
      product_precautionary_steps: "Langkah berjaga-jaga",
      product_precautionary_steps_of: "Langkah berjaga-jaga bagi ",
      product_side_effects: "Kesan Sampingan",
      product_side_effects_of: "Kesan Sampingan bagi ",
      product_frequently_ask_questions: "Soalan yang Kerap Ditanya",
      product_frequently_ask_questions_of: "Soalan yang Kerap Ditanya mengenai ",
      product_information_updated: "Maklumat dikemas kini pada: ",
      product_disclaimer: "Penafian",
      product_disclaimer_desc: "Kandungan laman web ini adalah bertujuan untuk memberi maklumat sahaja, bagi kegunaan para pengamal perubatan dan bukan bertujuan sebagai rujukan kepada pengguna untuk membuat sebarang pembelian atau menggantikan nasihat seorang pengamal perubatan. Keberkesanan dan kesan sampingan ubat-ubatan mungkin berbeza dari seorang pengguna dengan pengguna yang lain. Kami tidak menyarankan pengguna untuk membuat diagnosis atau rawatan sendiri. Pesakit haruslah sentiasa mendapatkan nasihat daripada doktor atau ahli farmasi bertauliah sebelum mengambil atau menggunakan sebarang ubat-ubatan. Isi kandungan laman web ini adalah terhad dan mungkin tidak merangkumi semua aspek tentang ubat-ubatan yang berkenaan. Perkhidmatan kami hanya bertujuan untuk menyokong dinamik antara doktor dan pesakit bukan menggantikannya. <br><br> Pemberian ubat-ubatan yang memerlukan preskripsi adalah tertakluk kepada penelitian kami terhadap preskripsi yang dikeluarkan oleh doktor yang berdaftar di bawah Majlis Perubatan Malaysia (MPM). Jika perlu, kami akan menyediakan perkhidmatan tele-konsultasi dengan salah seorang doktor panel kami yang berdaftar. Ini bukanlah iklan berkenaan ubat kerana iklan sedemikian memerlukan kebenaran dari Lembaga Iklan Ubat Malaysia.",
      product_available_area: "boleh didapati di banyak tempat di Malaysia. Kuala Lumpur, Bukit Bintang, Titiwangsa, Setiawangsa, Wangsa Maju, Kepong, Segambut, Bandar Tun Razak, Cheras, Subang Jaya, Petaling Jaya, Mont Kiara, Puchong, Bandar Sunway, TTDI, Seri Kembangan, Klang, Bukit Tinggi, Damansara, Sentul, Penang, George Town, Jelutong, Gelugor, Bayan Baru, Bandar Baru Air Itam, Sungai Ara, Bukit Mertajam, Butterworth, Perai, Johor Bahru, Skudai, Bukit Indah, Gelang Patah, Senai, Pasir Gudang, Taman Daya, Taman Molek, Taman Perling, Tebrau, Danga Bay, Larkin, Nusajaya, Pontian, Masai, Setia Tropika, Desaru, Tampoi. ",
      product_see_more: "Lihat Lagi",
      product_see_less: "Lihat Sedikit",
      product_unsure_medicine: "Kurang pasti dengan ubat anda?",
      product_get_help: "Minta bantuan daripada doktor bertauliah",
      product_consult_doctor: "Bercakap dengan Doktor",
      product_related_health_article: "Artikel Kesihatan Berkaitan",
      seo_product_title:"- Kegunaan, Dosage, Side Effects,Price, Benefits - DoctorOnCall", //TODO
      seo_main_title:"Farmasi Online Malaysia | Beli Ubat, Tanya Doktor Online",
      seo_meta_desc:"Beli ubat preskripsi & OTC dari farmasi online DoctorOnCall. Buat temujanji dengan doktor & hospital, tanya doktor soalan secara percuma,Dapat 20% diskaunt & penghantaran ubat percuma ",
      seo_meta_keyword: "Farmasi online, beli ubat preskripsi dan OTC, tanya doktor online, temujanji pakar & doktor, tanya doktor soalan percuma",
      site_doctoroncall: "DoctorOnCall",
      mainpage_search_doc: "Carian DoctorOnCall",
      mainpage_search_medicine: "Carian Ubat",
      mainpage_searchsuggestion_glucose_control : "Glucose Control",
      mainpage_searchsuggestion_cholestrol_management: "Cholestrol Management",
      mainpage_searchsuggestion_blood_pressure: "Blood Pressure Control",
      mainpage_searchsuggestion_mens_condition: "Men's Condition",
      mainpage_searchsuggestion_birth_control: "Birth Control",
      mainpage_search_history: "Search History",
      mainpage_order_medication: "Farmasi Online", //Pembelian Ubat ubatan
      mainpage_book_appointment: "Temujanji Doktor", //Buat Temujanji
      mainpage_consult_doctor: "Hubungi Doktor", //Bercakap dengan Doktot
      mainpage_ask_question: "Tanya Doktor", //Tanya Soalan Percuma
      mainpage_health_articles_days: "hari lalu",
      mainpage_health_articles_years : "tahun pengalaman",
      mainpage_health_articles_gp: "Doktor Perubatan Am",
      mainpage_pharma_order_medicine: "Farmasi Online", //Beli Ubat Secara Online
      mainpage_pharma_order_medicine_desc: "100% Ubat-Ubatan Tulen, penghantaran pada hari yang sama. Konsultasi dengan doktor berdaftar secara peribadi",
      mainpage_pharma_medicine: "Ubat",
      mainpage_pharma_wellness_lifestyle: "Kesihatan",
      mainpage_pharma_personal_care: "Peribadi",
      mainpage_pharma_lipitor_tablet: "Lipitor 20mg Tablet",
      mainpage_pharma_price_RM42: "RM 42.00",
      mainpage_pharma_add_to_cart: "Beli Sekarang",
      mainpage_pharma_crestor_tablet: "Crestor 10mg Tablet",
      mainpage_pharma_price_RM112: "RM 112.00",
      mainpage_plavix_tablet: "Plavix 75mg Tablet",
      mainpage_pharma_price_RM105: "RM 105.00",
      mainpage_pharma_norvasc_tablet: "Norvasc 5mg Tablet",
      mainpage_pharma_price_RM18: "RM 18.00",
      mainpage_pharma_aspirin: "Aspirin Cardio 100mg",
      mainpage_pharma_price_RM3_9: "RM 3.90 ",
      mainpage_pharma_flavette_tablet: "Flavettes Effervescent <br>Glow Tablet",
      mainpage_pharma_price_RM55: "RM 55.00",
      mainpage_pharma_rate_4_8: "(4.8)",
      mainpage_pharma_blackmore_vitamin: "Blackmores Buffered <br>Vitamin C",
      mainpage_pharma_rate_4_7: "(4.7)",
      mainpage_pharma_price_RM43_02: "RM 43.02",
      mainpage_pharma_neurobion: "Neurobion 10’s",
      mainpage_pharma_price_RM13_8: "RM 13.80",
      mainpage_pharma_berocca_tablet: "Berocca Effervescent <br>Tablet",
      mainpage_pharma_price_RM61_6: "RM 61.60",
      mainpage_pharma_blackmore_mineral_tablet: "Blackmores Multivitamins <br>+ Minerals Tablet",
      mainpage_pharma_price_RM32_8: "RM 32.80",
      mainpage_pharma_alpecin_shampoo: "Alpecin Caffeine Hybrid Shampoo",
      mainpage_pharma_price_RM34: "RM 34.00",
      mainpage_pharma_audace_tonic: "Audace Hair Tonic",
      mainpage_pharma_rate_4_5: "(4.5)",
      mainpage_pharma_price_RM47_92: "RM 47.92",
      mainpage_pharma_ripded_lotion: "Ridped Lotion",
      mainpage_pharma_rate_4_4: "(4.4)",
      mainpage_pharma_price_RM12: "RM 12.00",
      mainpage_pharma_selsun_suspension: "Selsun 2.5% Suspension",
      mainpage_pharma_price_RM43_70: "RM 43.70",
      mainpage_pharma_pantene_shampoo: "Pantene Hair Fall Shampoo",
      mainpage_pharma_price_RM15_90: "RM 15.90",
      mainpage_consult_doctor_online: "Konsultasi Doktor Secara Online", //Bercakap dengan Doktor Secara Online
      mainpage_consult_doctor_desc: "Berhubung dengan doktor yang berdaftar dengan Majlis Perubatan Malaysia dan dapatkan perkhidmatan yang anda inginkan melalui 3 langkah mudah",
      mainpage_consultdoc_step1: "1",
      mainpage_consultdoc_signup: "Daftar </a> atau Log Masuk<br> ke DoctorOnCall",
      mainpage_consultdoc_step2: "2",
      mainpage_consultdoc_speak_with_doc: "Bercakap dengan doktor dan dapatkan <br> rawatan dan jawapan kepada masalah anda",
      mainpage_consultdoc_step3: "3",
      mainpage_consultdoc_receive_med: "Dapatkan Ubat-Ubatan Anda - <br>Dihantar terus ke rumah! ",
      mainpage_book_doctor_appointment: "Buat temujanji dengan doktor",
      mainpage_book_doctor_appointment_desc: "Buat temujanji dengan pakar seluruh Malaysia dari pelbagai cawangan klinik dan hospital",
      mainpage_bookdoc_pediatrician: "Pakar Kanak-Kanak",
      mainpage_bookdoc_orthopaedic: "Pakar Tulang",
      mainpage_bookdoc_obstetrician_gynecologist: "Pakar Kesihatan Wanita",
      mainpage_bookdoc_cardiologist: "Pakar Jantung",
      mainpage_bookdoc_ear_nose_throat_specialist: "Pakar Telinga Hidung & Tekak",
      mainpage_bookdoc_dermatologist: "Pakar Kulit",
      mainpage_health_article: "Artikel Kesihatan",
      mainpage_health_article_desc: "Tambah info kesihatan anda secara pantas dengan jawapan daripada doktor berdaftar",
      mainpage_category_general_health: "Kesihatan Am",
      mainpage_category_mens_health: "Kesihatan Lelaki",
      mainpage_category_womens_health: "Kesihatan Wanita",
      mainpage_category_sexual_health: "Kesihatan Seksual",
      mainpage_category_eye_condition: "Sakit Mata",
      mainpage_category_sore_throat: "Sakit Tekak",
      mainpage_category_migraine: "Migrain",
      mainpage_category_minor_injury: "Kecederaan kecil",
      mainpage_category_fatty_liver: "Penyakit Hati",
      mainpage_category_cough_cold: "Batuk Selsema",
      mainpage_category_dengue: "Denggi",
      mainpage_category_constipation: "Sembelit",
      mainpage_category_skin_condition: "Masalah Kulit",
      mainpage_category_asthma: "Asma",
      mainpage_category_acid_reflux: "Asid Refluks",
      mainpage_category_erectile_dysfunction: "Mati Pucuk",
      mainpage_category_premature_ejaculation: "Ejakulasi Pramatang",
      mainpage_category_vaginal_discharge: "Keputihan",
      mainpage_category_missed_period: "Haid Lewat",
      mainpage_category_uti: "Kencing Kotor",
      mainpage_category_irregular_period: "Haid Tidak Teratur",
      mainpage_category_birth_control: "Perancangan Keluarga",
      mainpage_category_syphilis: "Sifilis",
      mainpage_category_hiv: "HIV",
      mainpage_category_herpes: "Herpes",
      mainpage_category_gonorrhea: "Gonorea",
      mainpage_ask_doctor: "Tanya Doktor",
      mainpage_ask_doctor_desc: "Tanya soalan tentang kesihatan secara sulit dan dapatkan jawapan daripada doktor berdaftar dengan segera",
      mainpage_askdoc_kencing_manis: "Kencing Manis",
      mainpage_askdoc_kencing_manis_question: "Sometimes I feel my tummy keeps on contracting once in a while but I can still feel the baby’s movement. Should I visit my doctor?",
      mainpage_askdoc_dr_sashini: "Dr Sashini",
      mainpage_askdoc_general_practitioner: "General Practitioner",
      mainpage_askdoc_mati_pucuk: "Mati Pucuk",
      mainpage_askdoc_mati_pucuk_question: "Bagaimana Slidenafil Ubat Viagra<br> Berkesan Dan Cara Pengunaan",
      mainpage_askdoc_keputihan: "Keputihan",
      mainpage_askdoc_keputihan_desc: "Penyebab, Diagnosis, Pengubatan Dan Pencegahan Penyakit Keputihan",
      mainpage_askdoc_vaginosis: "Vaginosis",
      mainpage_askdoc_vaginosis_question: "Apakah penyakit Vaginosis bakteria dan rawatannya?",
      mainpage_askdoc_urti: "URTI",
      mainpage_askdoc_urti_question: "Apakah URTI Dan Cara Mengelakkan Jangkitan?",
      mainpage_askdoc_haid_sakit: "Haid Sakit",
      mainpage_askdoc_haid_sakit_question: "Apakah senggugut dan bagaimana mencegah dan merawat?",
      mainpage_askdoc_vulvitis: "Vulvitis",
      mainpage_askdoc_vulvitis_question: "Apakah penyakit Vulvitis dan rawatan sesuai?",
      mainpage_askdoc_penyakit_kelamin: "Penyakit Kelamin",
      mainpage_askdoc_penyakit_kelamin_question: "Penyebab, Gejala, Diagnosis Dan Ubat Sesuai Untuk Penyakit Kelamin",
      mainpage_next_page: "Halaman Seterusnya",
      mainpage_connect_doctor_instant: "Hubungi doktor dengan segera", //Berhubung dengan doktor dalam masa yang singkat
      mainpage_connect_doctor_desc: "Buat panggilan telefon, video atau chat dengan doktor yang berdaftar di bawah MPM", //Berhubung dengan doktor berdaftar MPM melalui audio, chat atau video
      mainpage_connect_doctor: "Hubungi doktor", //Berhubung dengan seorang doktor
      mainpage_featured_on: "Seperti yang terpapar di",
      mainpage_subscribe_health_insight: "Langgan info kesihatan secara percuma",
      mainpage_subscribe_desc: "Dapatkan pemberitahun tentang artikel, tawaran dan promosi terbaru kami. Anda boleh berhenti melanggan pada bila-bila masa. ",
      mainpage_subscribe: "Langgan",
      tanya: "/tanya/",

      stats_overview_text:"Keseluruhan Statistik",
      stats_overview_confirmed_text:"Disahkan",
      stats_overview_recovered_text:"Pemulihan",
      stats_overview_death_text:"Kematian",
      stats_update:"Dikemaskini",
      continue_website:"Teruskan Ke Laman Web",
      consult_with_the:"Berunding dengan",
      moh_text:"Kementerian Kesihatan Malaysia",
      tweet_from_moh:"Tweets dari Laman Rasmi MOH",

      load_more_content_corona:"Lihat Lagi",
      see_less_content_corona:"Kurangkan",
      read_more_corona:"Baca Lagi",
      novel_corona_virus:"Novel Coronavirus",
      novel_corona_virus_desc:"Sejak hari pertama kami dimaklumkan, WHO telah bekerjasama dengan pihak berkuasa China dan pakar global untuk mengetahui lebih lanjut tentang virus, bagaimana ia mempengaruhi pesakit, bagaimana pesakit boleh dirawat dan tindakan yang boleh dilakukan oleh negara sebagai respons",
      ihr_corona_virus_text:"Jawatankuasa Kecemasan IHR akan bersidang semula untuk membahas tentang novel coronavirus di China",
      who_corona_virus_text:"WHO dan pemimpin China membincangkan langkah seterusnya dalam memerangi jangkitan coronavirus",
      missionsummary_corona_virus_text:"Ringkasan misi: Lawatan Lapangan WHO ke Wuhan, China 20-21 Januari 2020",
      corona_consult_doc:"Konsult dengan doktor sekarang",
      corona_consult_doc_desc:"Risau tentang simptom yang anda alami? Konsult dengan doktor kami sekarang.",
      consult_doc_btn_corona:"Konsult Doktor",
      try_answer_qustion_coronavirus:"Kita cuba untuk menjawab soalan anda",
      try_answer_qustion_subtext:"Kami mempunyai doktor yang bersedia untuk menjawab soalan anda secara PERCUMA.",
      what_is_novel_corona:"Apakah itu 2019 Novel Coronavirus (2019-nCov)?",
      novel_corona_definition:"2019-nCoV merupakan virus baru dalam keluarga coronavirus yang pernah menyebabkan Sindrom Pernafasan Akut Yang Teruk (SARS) pada tahun 2002 dan Sindrom Pernafasan Timur Tengah (MERS) pada tahun 2014.",
      ask_question_btn_corona:"Tanya Soalan Anda",
      no_panic_corona:"Tidak perlu panik.",
      list_frequently_question:"Kami senaraikan beberapa soalan yang kerap ditanya tentang Novel Coronavirus.",
      think_nov_virus_text:"Think you know all about Novel CoronaVirus (nCoV)?",
      take_quiz_btn:"Take A Quiz To Find Out!",
      why_call_corona:"Why is it called Novel Coronavirus?",
      why_call_corona_answer:"Novel means new and Novel Coronavirus means a new type of coronavirus that has not been identified previously.",
      where_come_from_corona:"Where does it come from?",
      where_come_from_corona_answer:"It is believed from the sample taken from the infected patients, the virus traced back to the local exotic market in Wuhan, Hubei Province, China.",
      how_infect_human:"How does the virus infect humans?",
      how_infect_human_answer:"The virus does infect from human-to-human although originally it may infect from animal-to-human. The mode of transmission is still unclear but as with other respiratory viruses, it may infect through water droplets (from sneezing or coughing).",
      can_virus_transmit:"Can the virus transmit from human to human?",
      can_virus_transmit_answer:"Yes it can.",
      how_long_incubation:"Bolehkah virus ini tersebar dari manusia ke manusia?",
      how_long_incubation_answer:"Virus ini boleh tersebar dari manusia ke manusia melalui cara berikut: <ul><li>Bersin ataupun batuk.</li><li>Rembesan cecair daripada badan seperti hingus.</li><li>Sentuhan seperti bersalaman.</li><li>Sentuhan terhadap barangan seperti tombol pintu yang telah dicemari virus.</li><li>Terkena najis yang telah dijangkiti virus ini.</li></ul>",

      corona_faq_7_title:"Adakah ia boleh berjangkit semasa tempoh pengeraman?",
    corona_faq_7_desc:"Setakat ini, belum ada kajian perubatan yang sahih membuktikan bahawa virus ini boleh menjangkiti seseorang ketika tempoh pengeraman. Namun berdasarkan kajian terbitan Jurnal Lancet, virus ini berpotensi untuk menjangkiti seseorang ketika tempoh pengeraman.",
    corona_faq_8_title:"Adakah virus ini sama dengan virus MERs-Cov atau SARS?",
    corona_faq_8_desc:"Tidak. Kedua-dua virus ini adalah berbeza cumanya mereka datang dari keluarga yang sama iaitu Coronavirus yang juga menyebabkan wabak MERs-CoV, SARS dan kini 2019-nCoV.",
    corona_faq_9_title:"Adakah ia sama dengan virus influenza?",
    corona_faq_9_desc:"Tidak. Coronavirus adalah berbeza dengan virus influenza dan datang daripada keluarga virus yang berlainan walaupun kedua-duanya menunjukkan simptom yang hampir sama pada pesakit.",
    corona_faq_10_title:"Bagaimanakah saya boleh melindungi diri saya daripada dijangkiti oleh virus ini?",
    corona_faq_10_desc:"Berdasarkan garis panduan yang telah dikeluarkan oleh Bahagian Kawalan Penyakit Malaysia, anda digalakkan untuk melakukan langkah pencegahan seperti berikut:<ul><li>Mencuci tangan dengan sabun dan air.</li><li>Elakkan daripada menyentuh mata, hidung atau mulut dengan tangan yang tidak dicuci.</li><li>Jauhi daripada orang yang sakit terutamanya yang menunjukkan simptom jangkitan Coronavirus</li><li>Elakkan daripada mengunjung kawasan tumpuan ramai orang</li><li>Elakkan daripada memakan daging mentah atau yang tidak dimasak dengan sempurna</li><li>Pastikan mulut serta hidung ditutup dengan tisu ketika batuk atau bersin dan buang tisu ke tong sampah</li><li>Cuci permukaan objek atau barangan secara berkala.</li></ul>",



    corona_faq_11_title:"Bolehkah saya mendapat vaksin bagi 2019-nCov?",
    corona_faq_11_desc:"Setakat ini, belum ada vaksin yang boleh diberikan untuk mencegah virus ini.",
    corona_faq_12_title:"Adakah virus ini berasal daripada vaksin?",
    corona_faq_12_desc:"Virus ini bukan berasal daripada vaksin. Ia dipercayai berevolusi dari virus yang sebelum ini hanya dijumpai pada haiwan eksotik seperti ular dan kelawar yang kemudiannya menjangkiti manusia.",
    corona_faq_13_title:"Adakah topeng muka boleh melindungi saya daripada virus ini?",
    corona_faq_13_desc:"Topeng muka tidak melindungi anda sepenuhnya kerana jangkitan ini boleh berlaku dari medium lain selain pernafasan. Namun pemakaian topeng dapat mengurangkan risiko jangkitan.",
    corona_faq_14_title:"Topeng muka mana yang harus saya gunakan untuk melindungi diri saya?",
    corona_faq_14_desc:"Topeng muka yang ideal bagi mencegah virus ini adalah topeng muka jenis 3ply yang juga digunakan untuk pembedahan dan ia merupakan topeng muka jenis pakai buang. Selain itu, topeng N95 juga boleh digunakan dan ia boleh digunakan secara berulang.",
    corona_faq_15_title:"Apa yang perlu saya lakukan jika saya telah terdedah dengan seseorang yang telah dijangkiti virus ini?",
    corona_faq_15_desc:"Anda dinasihatkan agar sentiasa peka dan memerhatikan tanda-tanda jangkitan seperti sesak nafas ataupun demam sekurang-kurangnya selama 14 hari. Jika anda mula untuk menunjukkan simptom Coronavirus, anda perlulah melaporkan diri ke hospital ataupun klinik dengan kadar segera.",
    // Symptoms of Coronavirus
    corona_faq_16_title:"Apakah tanda-tanda seseorang yang telah dijangkiti?",
    corona_faq_16_desc:"Pesakit akan mengalami simptom seperti berikut:<ol><li>Sakit tekak</li><li>Batuk</li><li>Selsema</li><li>Demam</li><li>Sesak nafas</li><li>Sakit badan</li></ol>",
    corona_faq_17_title:"Berapa lamakah masa yang diambil untuk gejala jangkitan ini timbul?",
    corona_faq_17_desc:"Gejala jangkitan akan timbul dalam jangka masa 14 hari.",
    corona_faq_18_title:"Apa yang perlu saya lakukan jika saya mempunyai gejala jangkitan ini?",
    corona_faq_18_desc:"Anda perlulah untuk mendapatkan khidmat perubatan dan melaporkan diri ke klinik ataupun hospital terdekat. Anda juga ditegah daripada pergi ke tempat kerja ataupun sekolah bagi mengelakkan anda menjangkiti orang lain.",
    corona_faq_19_title:"Apakah komplikasi yang boleh berlaku kepada seseorang yang dijangkiti oleh 2019-nCov?",
    corona_faq_19_desc:"Antara komplikasi yang boleh berlaku adalah seperti kegagalan buah pinggang, jangkitan paru-paru, kegagalan sistem pernafasan dan juga kematian.",
    // Diagnosis of Coronavirus
    corona_faq_20_title:"Bagaimanakah ujian untuk mengesan 2019-nCov dijalankan?",
    corona_faq_20_desc:"Darah pesakit akan diambil dan genetik virus dalam badan akan diperiksa melalui kaedah Polymerase Chain Reaction.",


    corona_faq_21_title:"Perlukah saya mendapatkan ujian bagi mengesan virus ini?",
    corona_faq_21_desc:"Pengendalian ujian ini adalah bergantung kepada pengamatan dan evaluasi daripada doktor setelah melakukan pemerhatian klinikal, pemeriksaan serta mengetahui sejarah sakit. Jika anda menunjukkan simptom jangkitan dan pernah berkunjung ataupun berada dekat dengan penduduk dari Wuhan, China dalam jangka masa yang panjang, sebaiknya anda mendapatkan ujian ini.",
    corona_faq_22_title:"Bagaimanakah saya boleh diuji untuk 2019-nCov?",
    corona_faq_22_desc:"Pengendalian ujian ini bergantung kepada pengamatan dan evaluasi daripada doktor setelah melakukan pemerhatian klinikal, pemeriksaan serta mengetahui sejarah sakit. Jika anda menunjukkan simptom jangkitan dan pernah berkunjung ataupun berada dekat dengan penduduk dari Wuhan, China dalam jangka masa yang panjang, sebaiknya anda mendapatkan ujian ini. Darah anda akan diambil untuk tujuan pengesanan virus.",
    // Travel Safety
    corona_faq_23_title:"Adakah selamat untuk saya ke China?",
    corona_faq_23_desc:"Menurut World Health Organisation WHO jumlah jangkitan serta kematian akibat wabak ini semakin meningkat. Oleh itu, anda disarankan untuk tidak berkunjung ke China dalam masa terdekat kecuali untuk urusan penting yang tidak dapat dielakkan.",
    corona_faq_24_title:"Adakah selamat untuk saya pergi ke negara lain?",
    corona_faq_24_desc:"Walaupun wabak ini sudah mula merebak ke negara lain namun anda masih boleh untuk berkunjung ke negara lain dan setiap negara juga ada kawalan kesihatan masing-masing.",
    corona_faq_25_title:"Bolehkah anak saya pergi ke sekolah?",
    corona_faq_25_desc:"Anak anda masih boleh untuk menghadiri kelas seperti biasa kecuali jika anak anda menunjukkan simptom ataupun rakan sekolahnya telah disahkan dijangkiti virus ini. Anda dinasihati agar mengikut perkembangan terkini sekolah terutamanya berita tengan jangkitan virus ini.",
    corona_faq_26_title:"Saya baru pulang dari lawatan ke China dan jatuh sakit. Apa yang patut saya buat?",
    corona_faq_26_desc:"Sebagai langkah berjaga-jaga anda perlulah melapor diri ke hospital ataupun klinik terdekat dengan kadar segera.",
    corona_faq_27_title:"Adakah saya perlu mengasingkan diri sekiranya saya baru pulang dari China?",
    corona_faq_27_desc:"Anda dinasihatkan agar sentiasa peka dan memerhatikan tanda-tanda jangkitan seperti sesak nafas ataupun demam sekurang-kurangnya selama 14 hari. Jika anda mula untuk menunjukkan simptom Coronavirus, anda perlulah melaporkan diri ke hospital ataupun klinik dengan kadar segera.",
    // Other FAQ’s about Coronavirus
    corona_faq_28_title:"Apakah risiko mendapat jangkitan dari pakej atau produk yang diterima dari China?",
    corona_faq_28_desc:"Setakat ini masih belum ada bukti mengatakan bahawa virus ini boleh hidup lama di luar badan manusia iaitu lebih daripada 24 jam. Namun anda masih perlu untuk melakukan langkah pencegahan iaitu dengan mengelap permukaan barangan dengan menggunakan tisu yang diletakkan ‘sanitizer’.",
    corona_faq_29_title:"Adakah selamat untuk mengambil produk haiwan atau makan daging haiwan yang diimport dari China?",
    corona_faq_29_desc:"Setakat ini, tiada bukti sahih mengatakan bahawa pengambilan produk haiwan atau makanan daging dari China boleh untuk menyebabkan jangkitan. Namun sebagai langkah berjaga-jaga anda dinasihati agar mengurangkan pengambilan produk haiwan yang diimport dari China.",
    corona_faq_30_title:"Bolehkah binatang peliharaan atau haiwan lain menyebarkan 2019-nCov?",
    corona_faq_30_desc:"Kes pertama yang dilaporkan adalah jangkitan daripada haiwan kepada manusia namun kini ia boleh merebak sesama manusia. Setakat ini, masih belum ada bukti mengatakan bahawa ia boleh disebarkan daripada bintang peliharaan.",
    
    
    corona_faq_31_title:"Bolehkah haiwan dijangkiti virus ini daripada manusia?",
    corona_faq_31_desc:"Setakat ini, belum ada bukti mengatakan bahawa manusia yang dijangkiti virus ini boleh untuk menyebarkan ia kepada haiwan.",
    corona_faq_32_title:"Adakah virus ini boleh meragut nyawa?",
    corona_faq_32_desc:"Ya, virus ini boleh menyebabkan banyak komplikasi kesihatan seperti kegagalan sistem pernafasan, kegagalan buah pinggang dan akhirnya menyebabkan kematian.",
    corona_faq_33_title:"Adakah terdapat rawatan atau ubat untuk menyembuhkan jangkitan virus ini?",
    corona_faq_33_desc:"Setakat ini, pesakit Coronavirus di China dirawat menggunakan ubat yang sama digunkan untuk merawat pesakit HIV.",
    corona_faq_34_title:"Berapa banyak kematian yang telah disebabkan oleh virus ini?",
    corona_faq_34_desc:"Setakat 30 Januari 2020, jumlah kematian yang telah direkod dan disahkan oleh WHO adalah sebanyak 170 orang.",
    corona_faq_35_title:"Adakah seseorang pasti akan mati jika dijangkiti virus ini?",
    corona_faq_35_desc:"Pesakit yang dijangkiti virus ini tidak semestinya berakhir dengan kematian dan kini hanya 170 pesakit yang telah meninggal dunia daripada 8000 jumlah jangkitan yang dilaporkan.",
    corona_faq_36_title:"Siapakah yang berisiko untuk dijangkiti virus ini?",
    corona_faq_36_desc:"Golongan yang berisiko adalah golongan yang mempunyai daya tahan badan yang rendah seperti pesakit HIV, pesakit cancer, pesakit kronik seperti kencing manis, kanak-kanak,  golongan emas, ibu mengandung dan juga seseorang yang berkunjung ke Wuhan,China dalam sebulan dua yang lepas.",
    corona_faq_37_title:"Bolehkah ia menjangkiti orang yang sihat?",
    corona_faq_37_desc:"Ya, virus ini boleh menjangkiti orang sihat.",
    corona_faq_38_title:"Adakah saya perlu mengelakkan makanan tertentu?",
    corona_faq_38_desc:"Anda dinasihati untuk mengamalkan pemakanan yang seimbang dan elakkan daripada mengambil makanan dariapda haiwan eksotik.",
    corona_faq_39_title:"Adakah saya perlu mengelak daripada memakan makanan yang diimport dari China?",
    corona_faq_39_desc:"Setakat ini, tiada bukti sahih mengatakan bahawa pengambilan makanan yang diimport dari China boleh untuk menyebabkan jangkitan. Namun sebagai langkah berjaga-jaga anda dinasihati agar mengurangkan pengambilan produk haiwan yang diimport dari China.",      
    corona_faq_40_title:"Adakah pengambilan vitamin C boleh membantu merawat atau mencegah jangkitan virus ini?",
    corona_faq_40_desc:"Setakat ini tiada kajian mengatakan bahawa Vitamin C berpotensi untuk membunuh virus ini.",

    
    corona_faq_41_title:"Apakah jenis makanan tambahan yang perlu saya ambil untuk mencegah jangkitan?",
    corona_faq_41_desc:"Tiada makanan tambahan ataupun suplemen yang terbukti oleh mana-mana badan perubatan untuk membantu menangani Coronavirus ini.",
    corona_faq_42_title:"Apakah status jangkitan ini di Malaysia?",
    corona_faq_42_desc:"Setakat ini terdapat 7 kes dilaporkan positif coronavirus namun tiada kematian berlaku.",
    corona_faq_43_title:"Bagaimana saya dapat menilai tahap kesihatan saya dari rumah sebelum ke hospital jika saya tidak sihat?",
    corona_faq_43_desc:"Anda boleh untuk memeriksa suhu badan menggunakan termometer untuk mengetahui suhu badan. Anda juga perlu peka jika pernah berkunjung ke China dalam jangka masa sebulan dua ini dan juga mengalami simptom jangkitan.",
    corona_faq_44_title:"Hospital mana yang boleh saya pergi jika saya berasa tidak sihat?",
    corona_faq_44_desc:"Anda boleh pergi ke mana-mana hospital dan klinik berdekatan tidak kira kerajaan mahupun swasta",
    corona_faq_45_title:"Bolehkah saya mengumpul kahak saya sendiri untuk dihantar untuk ujian makmal?",
    corona_faq_45_desc:"Anda tidak perlu untuk mengumpul kahak kerana proses ini perlulah dijalankan dengan teliti bagi mengelakkan pencemaran yang akhirnya mempengaruhi ketepatan keputusan. Pihak pengamal perubatan akan melakukan pengumpulan ini untuk anda.",
    corona_faq_46_title:"Bolehkan virus ini dibasmi dengan memasak daging haiwan yang telah dijangkiti?",
    corona_faq_46_desc:"Setakat ini belum ada bukti atau kajian menunjukkan bahawa virus ini boleh dibasmi jika dimasak atau dibunuh menggunakan suhu yang tinggi.",
    corona_faq_47_title:"Bolehkah saya pergi ke China atau Hong Kong?",
    corona_faq_47_desc:"Anda dinasihati agar tidak berkunjung ke China buat masa kini. Bagi negara lain yang juga mencatatkan kes tinggi jangkitan Coronavirus seperti Hong Kong, anda juga tidak digalakkan untuk ke negara tersebut sehingga wabak ini reda.",
    corona_faq_48_title:"Adakah antibiotik boleh membunuh virus ini?",
    corona_faq_48_desc:"Antibiotik tidak berupaya untuk membunuh mana -mana virus kerana ia hanya bertindak keatas kuman ataupun bakteria.",
    corona_faq_49_title:"Apakah peranan DoctorOnCall semasa wabak ini?",
    corona_faq_49_desc:"DoctorOnCall menjalankan kolaborasi bersama Kementerian kesihatan Malayasia KKM dalam menyediakan fakta yang benar, sahih dan terkini berkenaan dengan Wabak Coronavirus 2019.",
    corona_faq_50_title:"Di mana saya boleh mendapatkan lebih banyak maklumat dan status terkini mengenai 2019-nCov?",
    corona_faq_50_desc:"Anda boleh berkunjung ke laman sesawang atau protal rasmi Kementerian Kesihatan Malaysia dan juga laman facebook Kesihatan Awam Malaysia. Selain itu, sila ikut perkembangan lanjut berkenaan dengan isu ini di www.doctoroncall.com.my/coronavirus untuk mendapatkan informasi tepat lagi terkini."

  }
};

module.exports = library;