var library = {
  url: {
    subdir: "", // /medicine
    doc_page: "https://www.doctoroncall.com.my",
    checkout:"/checkout/#!/shopping_cart",
    signup_login: "/patient#/signup",
    find_doctor: "/find-doctor",
    medicine: "#",
    about_us: "/aboutUs",
    tanya: "/tanya",
    article: "/penyakit-a-z",
    faq: "#",
    media: "#",
    careers: "#",
    panel_doctors: "#",
    corporate_partnerships: "#",
    privacy_policy: "/privacyPolicy",
    terms_of_use: "/termsOfService",
    doctors_login: "/doctor#/signin",
    email: "mailto:contact@doctoroncall.com.my",
    tel_no: "tel:60384082000",
    doc_facebook: "https://www.facebook.com/doctoroncallMY/",
    doc_instagram: "https://www.instagram.com/doctoroncallmy/",
    doc_twitter: "https://twitter.com/doctoroncallmy",
    doc_whatsapp: "https://api.whatsapp.com/send?phone=60102721669&amp;text=DoctorOnCall 2019",
    footer_en_mens_health: "/mens-health",
    footer_en_womens_health: "/womens-health",
    footer_en_general_health: "/general-health",
    footer_en_sexual_health: "/sexual-health",
    footer_bm_mens_health: "/kesihatan-lelaki",
    footer_bm_womens_health: "/kesihatan-wanita",
    footer_bm_general_health: "/kesihatan",
    footer_bm_sexual_health: "/kesihatan-seksual",
    footer_hipertensi: "/hipertensi",
    footer_hipotensi: "/hipotensi",
    footer_hiv_aids: "/hiv-aids",
    footer_sinusitis: "/sinusitis",
    footer_menstruation: "/menstruasi",
    footer_buasir: "/buasir",
    footer_asma: "/asma",
    footer_diabetes: "/diabetess",
    footer_migrain: "/migrain",
    footer_klamidia: "/klamidia",
    footer_vaginosi_bakteria: "/vaginosis-bakteria",
    footer_vulvitis: "/vulvitis",
    footer_herpes_zoster: "/herpes-zoster",
    footer_HPV: "HPV-human-papillomavirus",
    footer_kutu: "/kutu",
    footer_haid: "/haid-sakit",
    footer_viagra: "/sildenafil-ubat-viagra",
    footer_vaginitis: "/vaginitis",
    footer_prediabetes: "/prediabetes",
    footer_hipertensi_pulmonal: "/hipertensi-pulmonal",
    footer_disfungsi_seksual: "/disfungsi-seksual",
    footer_herpes_genital: "/herpes-genital-herpes-simplex",
    footer_kolestrol_tinggi: "/kolesterol-tinggi",
    footer_strok: "/penyebab-dan-gejala-stroke-angin-ahmar",
    footer_hepatitisB: "/penyebab-penyakit-hepatitis-b",
    footer_jenis1_diabetes: "/penyebab-dan-gejala-diabetes-jenis-1",
    footer_psoriasis: "/penyebab-dan-gejala-psoriasis",
    footer_gallstones: "/penyebab-dan-gejala-penyakit-gallstones-batu-karang-hempedu",
    footer_ejakulasi_pramatang: "/ejakulasi-pramatang-premature-ejaculation",
    footer_sifilis: "/penyebab-dan-gejala-sifilis-syphilis",
    footer_gonore: "/gonore-gonorrhea-gejala-penyebab-dan-rawatan",
    footer_hepatitsA: "/hepatitis-a-penyebab-dan-gejala",
    footer_jenis2_diabetes: "/diabetes-jenis-2-kencing-manis-penyebab-dan-gejala",
    footer_hepatitisC: "/hepatitis-c-penyebab-dan-gejala",
    footer_impotensi: "/impotensi-impotence-penyebab-dan-gejala",
    footer_diabetes_insipidus: "/diabetes-insipidus-penyebab-dan-gejala",
    footer_kandidiasis: "/penyakit-kandidiasis-candidiasis",
    footer_penyakit_kelamin: "/penyakit-kelamin-sti",
    footer_sakit_tekak: "/sakit-tekak-sore-throat",
    footer_ketuat: "/sakit-ketuat-wart",
    footer_tiroid: "/penyakit-tiroid-thyroid",
    footer_tonsil: "/sakit-tonsil-tonsilitis",
  },
  en: {
    cart_item_added:"Item added to cart",
    header_order_medicine: "Order Medicine",
    header_book_appointment: "Book Appointment",
    header_consult_doctor: "Consult A Doctor",
    header_more: "More",
    header_about_us: "About Us",
    header_ask_question: "Ask a Question",
    header_read_article: "Read Health Articles",
    header_faq: "FAQ",
    header_media: "Media",
    header_careers: "Careers",
    header_panel_doctors: "Panel Doctors",
    header_corporate_partnerships: "Corporate Partnerships",
    header_contact_us: "Contact Us",
    header_bm_eng: "BM / ENG",
    header_button_signuplogin: "Sign Up / Login",
    footer_aboutdesc: "DoctorOnCall is Malaysia's first & largest online Doctor consultation platform that provides better healthcare services via chat, phone & video calls.",
    footer_button_readmore: "Read More",
    footer_services: "Our Services",
    footer_order_medicine: "Order Medicine",
    footer_consult_doctor: "Consult A Doctor",
    footer_ask_question: "Ask a Question",
    footer_read_article: "Read Health Articles",
    footer_search_hospitals: "Search Hospitals",
    footer_search_doctors: "Search Doctors",
    footer_book_appointment: "Book Appointment",
    footer_tanya_doktor: "Ask Doctor",
    footer_doctoroncall: "DoctorOnCall",
    footer_about_us: "About Us",
    footer_privacy: "Privacy",
    footer_faq: "FAQ",
    footer_contact_us: "Contact Us",
    footer_terms_of_use: "Terms of Use",
    footer_doctors_login: "Doctors Login",
    footer_media: "Media",
    footer_reach_us: "Contact Us",
    footer_social: "Social",
    footer_maps: "Map",
    footer_english: "English",
    footer_bahasa: "Bahasa",
    footer_health_centre: "Health Centre",
    footer_en_mens_health: "Men's Health",
    footer_en_womens_health: "Women's Health",
    footer_en_general_health: "General Health",
    footer_en_sexual_health: "Sexual Health",
    footer_bm_mens_health: "Kesihatan Lelaki",
    footer_bm_womens_health: "Kesihatan Wanita",
    footer_bm_general_health: "Kesihatan Umum",
    footer_bm_sexual_health: "Kesihatan Seksual",
    footer_hipertensi: "Hypertension",
    footer_hipotensi: "Hypotension",
    footer_hiv_aids: "HIV and AIDS",
    footer_sinusitis: "Sinusitis",
    footer_menstruation: "Menstruation",
    footer_buasir: "Hemorrhoids",
    footer_asma: "Asthma",
    footer_diabetes: "Diabetes",
    footer_migrain: "Migrain",
    footer_klamidia: "Chlamydia",
    footer_vaginosi_bakteria: "Bacterial vaginosis",
    footer_vulvitis: "Vulvitis",
    footer_herpes_zoster: "Herpes zoster",
    footer_HPV: "HPV",
    footer_kutu: "Lice",
    footer_haid: "Period pain",
    footer_viagra: "Viagra",
    footer_vaginitis: "Vaginitis",
    footer_prediabetes: "Prediabetes",
    footer_hipertensi_pulmonal: "Pulmonal hypertension",
    footer_disfungsi_seksual: "Sexual dysfunction",
    footer_herpes_genital: "Genital Herpes (Herpes Simplex)",
    footer_kolestrol_tinggi: "High cholestrol",
    footer_strok: "Stroke",
    footer_hepatitisB: "Hepatitis B",
    footer_jenis1_diabetes: "Type 1 Diabetes",
    footer_psoriasis: "Psoriasis",
    footer_gallstones: "Gallstones",
    footer_ejakulasi_pramatang: "Premature ejaculation",
    footer_sifilis: "Syphilis",
    footer_gonore: "Gonorrhea",
    footer_hepatitsA: "Hepatitis A",
    footer_jenis2_diabetes: "Type 2 Diabetes",
    footer_hepatitisC: "Hepatitis C",
    footer_impotensi: "Impotension",
    footer_diabetes_insipidus: "Diabetes insipidus",
    footer_kandidiasis: "Candidiasis - Introduction",
    footer_penyakit_kelamin: "Veneral disease - Introduction",
    footer_sakit_tekak: "Sore throat - single",
    footer_ketuat: "Warts",
    footer_tiroid: "Thyroid - Introduction",
    footer_tonsil: "Tonsilitis - Introduction",
    mainpage_shop_by_category: "Shop by Category",
    mainpage_medicine_drug: "Medicines and Prescription Drugs",
    mainpage_nutrition_vitamin_supplement: "Nutrition, Vitamins & Supplements",
    mainpage_personal_care: "Personal Care",
    mainpage_deliver_doorstep: "We deliver to your doorstep",
    mainpage_free_of_charge: "Free of charge",
    category_quick_filter: "Quick Filter",
    product_advise: "It is advised to speak to a medical professional before consuming this product",
    product_img_disclaimer:"The product images shown are for illustration purposes only and may not be an exact representation of the product",
    product_prescription_required: "Prescription Required",
    product_discount: "-20%",
    product_RM: "RM ",
    product_out_of_stock: "Out of Stock",
    product_manufactured_by: "Manufactured by",
    product_supplied_buy: "Supplied by",
    product_active_ingredient: "Active Ingredient",
    product_packaging: "Packaging",
    product_quantity: "Quantity",
    product_add_to_cart: "Add To Cart",
    product_check_out: "Check Out",
    product_not_in_stock: "Not In Stock",
    product_about_medicine: "About Medicine",
    product_description_of: "Description of ",
    product_usage: "Usage",
    product_how_to_take: "How to take",
    product_dosage_composition: "Dosage & Composition",
    product_dosage_composition_of: "Dosage & Composition of ",
    product_professional_opinion: "Professional Opinion",
    product_professional_opinion_of: "Professional Opinion of ",
    product_precautionary_steps: "Precautionary Steps",
    product_precautionary_steps_of: "Precautionary Steps of ",
    product_side_effects: "Side Effects",
    product_side_effects_of: "Side Effects of ",
    product_frequently_ask_questions: "Frequently Asked Questions",
    product_frequently_ask_questions_of: "Frequently Asked Questions of ",
    product_information_updated: "Information last updated on: ",
    product_disclaimer: "Disclaimer",
    product_disclaimer_desc: "The content provided on this webpage is to provide information only, to be fully-interpreted by a medical professional, and not intended as a guide to make purchase decisions, or a substitute to advice of a medical professional. Effectiveness and side effects of medication may differ from individual to individual. We do not encourage any customer to self-diagnose and/or self-medicate. Patients should always consult a medical professional before taking or using any medication. The content provided here is non-exhaustive and may not cover all aspects of the medication. Our service should only be used to support the doctor-patient dynamic, not replace it. <br><br>The fulfilment of prescription medication is subject to our review of a prescription issued by a Malaysian Medical Association (MMA) registered doctor. If required, we will provide a tele-consult service with one of our registered panel doctors. This is not an advertisement of a medicine as such an advertisement would require prior approval from the Medicines Advertisement Board of Malaysia.",
    product_available_area: "is available in many areas in Malaysia. Kuala Lumpur, Bukit Bintang, Titiwangsa, Setiawangsa, Wangsa Maju, Kepong, Segambut, Bandar Tun Razak, Cheras, Subang Jaya, Petaling Jaya, Mont Kiara, Puchong, Bandar Sunway, TTDI, Seri Kembangan, Klang, Bukit Tinggi, Damansara, Sentul, Penang, George Town, Jelutong, Gelugor, Bayan Baru, Bandar Baru Air Itam, Sungai Ara, Bukit Mertajam, Butterworth, Perai, Johor Bahru, Skudai, Bukit Indah, Gelang Patah, Senai, Pasir Gudang, Taman Daya, Taman Molek, Taman Perling, Tebrau, Danga Bay, Larkin, Nusajaya, Pontian, Masai, Setia Tropika, Desaru, Tampoi.",
    product_see_more: "See More",
    product_see_less: "See Less",
    product_unsure_medicine: "Unsure of your medicine?",
    product_get_help: "Get help from a certified doctor",
    product_consult_doctor: "Consult Doctor",
    product_related_health_article: "Related Health Articles",
    seo_product_title:"- Uses, Dosage, Side Effects,Price, Benefits - DoctorOnCall",
    seo_main_title:"DoctorOnCall | Malaysia's Doctors & Pharmacy In One Place Online",
    seo_meta_desc:"DoctorOnCall is the easiest way to buy prescribed medication online. Talk to a doctor through your phone & have your medicine delivered to your doorstep.",
    site_doctoroncall: "DoctorOnCall",
    },

  bm: {
    cart_item_added:"Dimasukan ke Troli", //TODO - translate
    header_order_medicine: "Beli Ubat",
    header_book_appointment: "Buat Temu Janji",
    header_consult_doctor: "Konsultasi bersama Doktor",
    header_more: "Lebih Lanjut",
    header_about_us: "Tentang Kami",
    header_ask_question: "Tanya Soalan",
    header_read_article: "Baca Artikel Kesihatan",
    header_faq: "FAQ",
    header_media: "Media",
    header_careers: "Kerjaya",
    header_panel_doctors: "Panel Doktor",
    header_corporate_partnerships: "Rakan Kongsi Korporat",
    header_contact_us: "Hubungi Kami",
    header_bm_eng: "BM / ENG",
    header_button_signuplogin: "Daftar / Log Masuk",
    footer_aboutdesc: "DoctorOnCall adalah platform konsultasi Doktor atas talian pertama & terbesar di Malaysia. Kami menyediakan perkhidmatan kesihatan melalui servis mesej, panggilan video & panggilan telefon.",
    footer_button_readmore: "Baca Lebih Lanjut ",
    footer_services: "Perkhidmatan Kami",
    footer_order_medicine: "Beli Ubat",
    footer_consult_doctor: "Konsultasi bersama Doktor",
    footer_ask_question: "Tanya Soalan",
    footer_read_article: "Baca Artikel Kesihatan",
    footer_search_hospitals: "Cari Hospital",
    footer_search_doctors: "Cari Doktor",
    footer_book_appointment: "Buat Temu Janji",
    footer_tanya_doktor: "Tanya Doktor (Soalan)",
    footer_doctoroncall: "DoctorOnCall",
    footer_about_us: "Tentang Kami",
    footer_privacy: "Privasi",
    footer_faq: "FAQ",
    footer_contact_us: "Hubungi Kami",
    footer_terms_of_use: "Terma Penggunaan",
    footer_doctors_login: "Log Masuk Doktor",
    footer_media: "Media",
    footer_reach_us: "Hubungi Kami",
    footer_social: "Sosial",
    footer_maps: "Peta",
    footer_english: "English",
    footer_bahasa: "Bahasa",
    footer_health_centre: "Pusat Kesihatan",
    footer_en_mens_health: "Men's Health",
    footer_en_womens_health: "Women's Health",
    footer_en_general_health: "General Health",
    footer_en_sexual_health: "Sexual Health",
    footer_bm_mens_health: "Kesihatan Lelaki",
    footer_bm_womens_health: "Kesihatan Wanita",
    footer_bm_general_health: "Kesihatan Umum",
    footer_bm_sexual_health: "Kesihatan Seksual",
    footer_hipertensi: "Hipertensi",
    footer_hipotensi: "Hipotensi",
    footer_hiv_aids: "HIV dan AIDS",
    footer_sinusitis: "Sinusitis",
    footer_menstruasi: "Menstruasi",
    footer_buasir: "Buasir",
    footer_asma: "Asma",
    footer_diabetes: "Diabetes",
    footer_migrain: "Migrain",
    footer_klamidia: "Klamidia",
    footer_vaginosis_bakteria: "Vaginosis bakteria",
    footer_vulvitis: "Vulvitis",
    footer_herpes_zoster: "Herpes zoster",
    footer_HPV: "HPV",
    footer_kutu: "Kutu",
    footer_haid_: "Haid-sakit",
    footer_viagra: "Viagra",
    footer_vaginitis: "Vaginitis",
    footer_prediabetes: "Prediabetes",
    footer_hipertensi_pulmonal: "Hypertensi pulmonal",
    footer_disfungsi_seksual: "Disfungsi seksual",
    footer_herpes_genital: "Herpes genital (herpes simplex)",
    footer_kolestrol_tinggi: "Kolestrol tinggi",
    footer_strok: "Strok",
    footer_hepatitisB: "Hepatitis B",
    footer_jenis1_diabetes: "Jenis 1 Diabetes",
    footer_psoriasis: "Psoriasis",
    footer_gallstones: "Gallstones",
    footer_ejakulasi_pramatang: "Ejakulasi pramatang",
    footer_sifilis: "Sifilis",
    footer_gonore: "Gonore",
    footer_hepatitsA: "Hepatitis A",
    footer_jenis2_diabetes: "Diabetes Jenis 2",
    footer_hepatitisC: "Hepatitis C",
    footer_impotensi: "Impotensi",
    footer_diabetes_insipidus: "Diabetes insipidus",
    footer_kandidiasis: "Kandidiasis - Pengenalan",
    footer_penyakit_kelamin: "Penyakit Kelamin - Pengenalan",
    footer_sakit_tekak: "Sakit tekak - single",
    footer_ketuat: "Ketuat",
    footer_tiroid: "Tiroid - Pengenalan",
    footer_tonsil: "Tonsil - pengenalan",
    mainpage_shop_by_category: "Beli Mengikut Kategori",
    mainpage_medicine_drug: "Ubat dan Preskripsi Ubat",
    mainpage_nutrition_vitamin_supplement: "Nutrisi, Vitamin & Suplemen",
    mainpage_personal_care: "Penjagaan Peribadi",
    mainpage_deliver_doorstep: "Kami menghantar sehingga ke pintu rumah anda",
    mainpage_free_of_charge: "Secara Percuma",
    category_quick_filter: "Tapisan Ringkas",
    product_advise: "Anda dinasihatkan untuk berunding dengan pakar perubatan sebelum mengambil produk ini",
    product_img_disclaimer:"The product images shown are for illustration purposes only and may not be an exact representation of the product",     //TODO: translate
    product_prescription_required: "Preskripsi Diperlukan",
    product_discount: "-20%",
    product_RM: "RM ",
    product_out_of_stock: "Kehabisan Stok",
    product_manufactured_by: "Dikilangkan oleh",
    product_supplied_buy: "Dibekalkan oleh",
    product_active_ingredient: "Bahan Aktif",
    product_packaging: "Pembungkusan",
    product_quantity: "Kuantiti",
    product_add_to_cart: "Masukkan ke Troli",
    product_check_out: "Semak Keluar", // Check Out // Still not sure //TODO
    product_not_in_stock: "Tiada Dalam Stok",
    product_about_medicine: "Tentang Ubat",
    product_description_of: "Penerangan tentang ",
    product_usage: "Penggunaan",
    product_how_to_take: "Cara Pengambilan",
    product_dosage_composition: "Sukatan dan Komposisi",
    product_dosage_composition_of: "Sukatan dan Komposisi untuk ",
    product_professional_opinion: "Nasihat Pakar",
    product_professional_opinion_of: "Nasihat Pakar mengenai ",
    product_precautionary_steps: "Langkah berjaga-jaga",
    product_precautionary_steps_of: "Langkah berjaga-jaga bagi ",
    product_side_effects: "Kesan Sampingan",
    product_side_effects_of: "Kesan Sampingan bagi ",
    product_frequently_ask_questions: "Soalan yang Kerap Ditanya",
    product_frequently_ask_questions_of: "Soalan yang Kerap Ditanya mengenai ",
    product_information_updated: "Maklumat dikemas kini pada: ",
    product_disclaimer: "Penafian",
    product_disclaimer_desc: "Kandungan laman web ini adalah bertujuan untuk memberi maklumat sahaja, bagi kegunaan para pengamal perubatan dan bukan bertujuan sebagai rujukan kepada pengguna untuk membuat sebarang pembelian atau menggantikan nasihat seorang pengamal perubatan. Keberkesanan dan kesan sampingan ubat-ubatan mungkin berbeza dari seorang pengguna dengan pengguna yang lain. Kami tidak menyarankan pengguna untuk membuat diagnosis atau rawatan sendiri. Pesakit haruslah sentiasa mendapatkan nasihat daripada doktor atau ahli farmasi bertauliah sebelum mengambil atau menggunakan sebarang ubat-ubatan. Isi kandungan laman web ini adalah terhad dan mungkin tidak merangkumi semua aspek tentang ubat-ubatan yang berkenaan. Perkhidmatan kami hanya bertujuan untuk menyokong dinamik antara doktor dan pesakit bukan menggantikannya. <br><br> Pemberian ubat-ubatan yang memerlukan preskripsi adalah tertakluk kepada penelitian kami terhadap preskripsi yang dikeluarkan oleh doktor yang berdaftar di bawah Majlis Perubatan Malaysia (MPM). Jika perlu, kami akan menyediakan perkhidmatan tele-konsultasi dengan salah seorang doktor panel kami yang berdaftar. Ini bukanlah iklan berkenaan ubat kerana iklan sedemikian memerlukan kebenaran dari Lembaga Iklan Ubat Malaysia.",
    product_available_area: "boleh didapati di banyak tempat di Malaysia. Kuala Lumpur, Bukit Bintang, Titiwangsa, Setiawangsa, Wangsa Maju, Kepong, Segambut, Bandar Tun Razak, Cheras, Subang Jaya, Petaling Jaya, Mont Kiara, Puchong, Bandar Sunway, TTDI, Seri Kembangan, Klang, Bukit Tinggi, Damansara, Sentul, Penang, George Town, Jelutong, Gelugor, Bayan Baru, Bandar Baru Air Itam, Sungai Ara, Bukit Mertajam, Butterworth, Perai, Johor Bahru, Skudai, Bukit Indah, Gelang Patah, Senai, Pasir Gudang, Taman Daya, Taman Molek, Taman Perling, Tebrau, Danga Bay, Larkin, Nusajaya, Pontian, Masai, Setia Tropika, Desaru, Tampoi. ",
    product_see_more: "Lihat Lagi",
    product_see_less: "Lihat Sedikit",
    product_unsure_medicine: "Kurang pasti dengan ubat anda?",
    product_get_help: "Minta bantuan daripada doktor bertauliah",
    product_consult_doctor: "Bercakap dengan Doktor",
    product_related_health_article: "Artikel Kesihatan Berkaitan",
    seo_product_title:"- Kegunaan, Dosage, Side Effects,Price, Benefits - DoctorOnCall", //TODO
    seo_main_title:"DoctorOnCall | Malaysia's Doctors & Pharmacy In One Place Online", //TODO
    seo_meta_desc:"DoctorOnCall is the easiest way to buy prescribed medication online. Talk to a doctor through your phone & have your medicine delivered to your doorstep.", //TODO
    site_doctoroncall: "DoctorOnCall",
  }
};

module.exports = library;
