var library = {
  url: {
    subdir: "", // /medicine
    doc_page: "https://www.doctoroncall.com.my",
    checkout:"/checkout/#!/shopping_cart",
    signup_login: "/patient#/signup",
    find_doctor: "/find-doctor",
    medicine: "#",
    about_us: "/aboutUs",
    tanya: "/tanya",
    article: "/penyakit-a-z",
    soalan: "/soalan",
    faq: "#",
    media: "#",
    careers: "#",
    panel_doctors: "#",
    corporate_partnerships: "#",
    privacy_policy: "/privacyPolicy",
    terms_of_use: "/termsOfService",
    doctors_login: "/doctor#/signin",
    email: "mailto:contact@doctoroncall.com.my",
    tel_no: "tel:+60384082000",
    doc_facebook: "https://www.facebook.com/doctoroncallMY/",
    doc_instagram: "https://www.instagram.com/doctoroncallmy/",
    doc_twitter: "https://twitter.com/doctoroncallmy",
    doc_whatsapp: "https://api.whatsapp.com/send?phone=60102721669&amp;text=DoctorOnCall 2019",
    footer_en_mens_health: "/mens-health",
    footer_en_womens_health: "/womens-health",
    footer_en_general_health: "/general-health",
    footer_en_sexual_health: "/sexual-health",
    footer_bm_mens_health: "/kesihatan-lelaki",
    footer_bm_womens_health: "/kesihatan-wanita",
    footer_bm_general_health: "/kesihatan",
    footer_bm_sexual_health: "/kesihatan-seksual",
    footer_hipertensi: "/hipertensi",
    footer_hipotensi: "/hipotensi",
    footer_hiv_aids: "/hiv-aids",
    footer_sinusitis: "/sinusitis",
    footer_menstruation: "/menstruasi",
    footer_buasir: "/buasir",
    footer_asma: "/asma",
    footer_diabetes: "/diabetess",
    footer_migrain: "/migrain",
    footer_klamidia: "/klamidia",
    footer_vaginosi_bakteria: "/vaginosis-bakteria",
    footer_vulvitis: "/vulvitis",
    footer_herpes_zoster: "/herpes-zoster",
    footer_HPV: "/HPV-human-papillomavirus",
    footer_kutu: "/kutu",
    footer_haid: "/haid-sakit",
    footer_viagra: "/sildenafil-ubat-viagra",
    footer_vaginitis: "/vaginitis",
    footer_prediabetes: "/prediabetes",
    footer_hipertensi_pulmonal: "/hipertensi-pulmonal",
    footer_disfungsi_seksual: "/disfungsi-seksual",
    footer_herpes_genital: "/herpes-genital-herpes-simplex",
    footer_kolestrol_tinggi: "/kolesterol-tinggi",
    footer_strok: "/penyebab-dan-gejala-stroke-angin-ahmar",
    footer_hepatitisB: "/penyebab-penyakit-hepatitis-b",
    footer_jenis1_diabetes: "/penyebab-dan-gejala-diabetes-jenis-1",
    footer_psoriasis: "/penyebab-dan-gejala-psoriasis",
    footer_gallstones: "/penyebab-dan-gejala-penyakit-gallstones-batu-karang-hempedu",
    footer_ejakulasi_pramatang: "/ejakulasi-pramatang-premature-ejaculation",
    footer_sifilis: "/penyebab-dan-gejala-sifilis-syphilis",
    footer_gonore: "/gonore-gonorrhea-gejala-penyebab-dan-rawatan",
    footer_hepatitsA: "/hepatitis-a-penyebab-dan-gejala",
    footer_jenis2_diabetes: "/diabetes-jenis-2-kencing-manis-penyebab-dan-gejala",
    footer_hepatitisC: "/hepatitis-c-penyebab-dan-gejala",
    footer_impotensi: "/impotensi-impotence-penyebab-dan-gejala",
    footer_diabetes_insipidus: "/diabetes-insipidus-penyebab-dan-gejala",
    footer_kandidiasis: "/penyakit-kandidiasis-candidiasis",
    footer_penyakit_kelamin: "/penyakit-kelamin-sti",
    footer_sakit_tekak: "/sakit-tekak-sore-throat",
    footer_ketuat: "/sakit-ketuat-wart",
    footer_tiroid: "/penyakit-tiroid-thyroid",
    footer_tonsil: "/sakit-tonsil-tonsilitis",
  },
  en: {
    cart_item_added:"Item added to cart",
    header_order_medicine: "Order Medicine",
    header_book_appointment: "Book Appointment",
    header_consult_doctor: "Consult A Doctor",
    header_more: "More",
    header_about_us: "About Us",
    header_ask_question: "Ask a Question",
    header_read_article: "Read Health Articles",
    header_faq: "FAQ",
    header_media: "Media",
    header_careers: "Careers",
    header_panel_doctors: "Panel Doctors",
    header_corporate_partnerships: "Corporate Partnerships",
    header_contact_us: "Contact Us",
    header_bm_eng: "BM / ENG",
    header_bm:"Bahasa",
    header_en:"English",
    header_button_signuplogin: "Sign Up / Login",
    footer_aboutdesc: "DoctorOnCall is Malaysia's first & largest online Doctor consultation platform that provides better healthcare services via chat, phone & video calls.",
    footer_button_readmore: "Read More",
    footer_services: "Our Services",
    footer_order_medicine: "Order Medicine",
    footer_consult_doctor: "Consult A Doctor",
    footer_ask_question: "Ask a Question",
    footer_read_article: "Read Health Articles",
    footer_search_hospitals: "Search Hospitals",
    footer_search_doctors: "Search Doctors",
    footer_book_appointment: "Book Appointment",
    footer_tanya_doktor: "Ask Doctor",
    footer_doctoroncall: "DoctorOnCall",
    footer_about_us: "About Us",
    footer_privacy: "Privacy",
    footer_faq: "FAQ",
    footer_contact_us: "Contact Us",
    footer_terms_of_use: "Terms of Use",
    footer_doctors_login: "Doctors Login",
    footer_media: "Media",
    footer_reach_us: "Contact Us",
    footer_social: "Social",
    footer_maps: "Map",
    footer_english: "English",
    footer_bahasa: "Bahasa",
    footer_health_centre: "Health Centre",
    footer_en_mens_health: "Men's Health",
    footer_en_womens_health: "Women's Health",
    footer_en_general_health: "General Health",
    footer_en_sexual_health: "Sexual Health",
    footer_bm_mens_health: "Kesihatan Lelaki",
    footer_bm_womens_health: "Kesihatan Wanita",
    footer_bm_general_health: "Kesihatan Umum",
    footer_bm_sexual_health: "Kesihatan Seksual",
    footer_hipertensi: "Hypertension",
    footer_hipotensi: "Hypotension",
    footer_hiv_aids: "HIV and AIDS",
    footer_sinusitis: "Sinusitis",
    footer_menstruation: "Menstruation",
    footer_buasir: "Hemorrhoids",
    footer_asma: "Asthma",
    footer_diabetes: "Diabetes",
    footer_migrain: "Migrain",
    footer_klamidia: "Chlamydia",
    footer_vaginosi_bakteria: "Bacterial vaginosis",
    footer_vulvitis: "Vulvitis",
    footer_herpes_zoster: "Herpes zoster",
    footer_HPV: "HPV",
    footer_kutu: "Lice",
    footer_haid: "Period pain",
    footer_viagra: "Viagra",
    footer_vaginitis: "Vaginitis",
    footer_prediabetes: "Prediabetes",
    footer_hipertensi_pulmonal: "Pulmonal hypertension",
    footer_disfungsi_seksual: "Sexual dysfunction",
    footer_herpes_genital: "Genital Herpes (Herpes Simplex)",
    footer_kolestrol_tinggi: "High cholestrol",
    footer_strok: "Stroke",
    footer_hepatitisB: "Hepatitis B",
    footer_jenis1_diabetes: "Type 1 Diabetes",
    footer_psoriasis: "Psoriasis",
    footer_gallstones: "Gallstones",
    footer_ejakulasi_pramatang: "Premature ejaculation",
    footer_sifilis: "Syphilis",
    footer_gonore: "Gonorrhea",
    footer_hepatitsA: "Hepatitis A",
    footer_jenis2_diabetes: "Type 2 Diabetes",
    footer_hepatitisC: "Hepatitis C",
    footer_impotensi: "Impotension",
    footer_diabetes_insipidus: "Diabetes insipidus",
    footer_kandidiasis: "Candidiasis - Introduction",
    footer_penyakit_kelamin: "Veneral disease - Introduction",
    footer_sakit_tekak: "Sore throat - single",
    footer_ketuat: "Warts",
    footer_tiroid: "Thyroid - Introduction",
    footer_tonsil: "Tonsilitis - Introduction",
    mainpage_shop_by_category: "Shop by Category",
    mainpage_medicine_drug: "Medicines and Prescription Drugs",
    mainpage_nutrition_vitamin_supplement: "Nutrition, Vitamins & Supplements",
    mainpage_personal_care: "Personal Care",
    mainpage_deliver_doorstep: "We deliver to your doorstep",
    mainpage_free_of_charge: "Free of charge",
    mainpage_order_now: "Go to E-Pharmacy Now",
    mainpage_consult_doctor_now: "Find Doctor Now",
    mainpage_appointment_now: "Book Appointment Now",
    mainpage_read_health: "Read Health Articles Now",
    mainpage_ask_doctor_now: "Ask Doctor Now",
    category_quick_filter: "Quick Filter",
    product_advise: "It is advised to speak to a medical professional before consuming this product",
    product_img_disclaimer:"The product images shown are for illustration purposes only and may not be an exact representation of the product",
    product_prescription_required: "Prescription Required",
    product_discount: "-20%",
    product_RM: "RM ",
    product_out_of_stock: "Out of Stock",
    product_manufactured_by: "Manufactured by",
    product_supplied_buy: "Supplied by",
    product_active_ingredient: "Active Ingredient",
    product_packaging: "Packaging",
    product_quantity: "Quantity",
    product_add_to_cart: "Add To Cart",
    product_check_out: "Check Out",
    product_not_in_stock: "Not In Stock",
    product_about_medicine: "About Medicine",
    product_description_of: "Description of ",
    product_usage: "Usage",
    product_how_to_take: "How to take",
    product_dosage_composition: "Dosage & Composition",
    product_dosage_composition_of: "Dosage & Composition of ",
    product_professional_opinion: "Professional Opinion",
    product_professional_opinion_of: "Professional Opinion of ",
    product_precautionary_steps: "Precautionary Steps",
    product_precautionary_steps_of: "Precautionary Steps of ",
    product_side_effects: "Side Effects",
    product_side_effects_of: "Side Effects of ",
    product_frequently_ask_questions: "Frequently Asked Questions",
    product_frequently_ask_questions_of: "Frequently Asked Questions of ",
    product_information_updated: "Information last updated on: ",
    product_disclaimer: "Disclaimer",
    product_disclaimer_desc: "The content provided on this webpage is to provide information only, to be fully-interpreted by a medical professional, and not intended as a guide to make purchase decisions, or a substitute to advice of a medical professional. Effectiveness and side effects of medication may differ from individual to individual. We do not encourage any customer to self-diagnose and/or self-medicate. Patients should always consult a medical professional before taking or using any medication. The content provided here is non-exhaustive and may not cover all aspects of the medication. Our service should only be used to support the doctor-patient dynamic, not replace it. <br><br>The fulfilment of prescription medication is subject to our review of a prescription issued by a Malaysian Medical Association (MMA) registered doctor. If required, we will provide a tele-consult service with one of our registered panel doctors. This is not an advertisement of a medicine as such an advertisement would require prior approval from the Medicines Advertisement Board of Malaysia.",
    product_available_area: "is available in many areas in Malaysia. Kuala Lumpur, Bukit Bintang, Titiwangsa, Setiawangsa, Wangsa Maju, Kepong, Segambut, Bandar Tun Razak, Cheras, Subang Jaya, Petaling Jaya, Mont Kiara, Puchong, Bandar Sunway, TTDI, Seri Kembangan, Klang, Bukit Tinggi, Damansara, Sentul, Penang, George Town, Jelutong, Gelugor, Bayan Baru, Bandar Baru Air Itam, Sungai Ara, Bukit Mertajam, Butterworth, Perai, Johor Bahru, Skudai, Bukit Indah, Gelang Patah, Senai, Pasir Gudang, Taman Daya, Taman Molek, Taman Perling, Tebrau, Danga Bay, Larkin, Nusajaya, Pontian, Masai, Setia Tropika, Desaru, Tampoi.",
    product_see_more: "See More",
    product_see_less: "See Less",
    product_unsure_medicine: "Unsure of your medicine?",
    product_get_help: "Get help from a certified doctor",
    product_consult_doctor: "Consult Doctor",
    product_related_health_article: "Related Health Articles",
    seo_product_title:"- Uses, Dosage, Side Effects,Price, Benefits - DoctorOnCall",
    seo_main_title:"Malaysia's Online Pharmacy | Order Medicine, Consult Doctor Online",
    seo_meta_desc:"Buy prescription & OTC medicines online on DoctorOnCall's pharmacy. Book appointment with doctors & hospitals, ask free health questions,consult specialist online. Get 20% off & free delivery on purchase of medicines",
    seo_meta_keyword: "Online Pharmacy, Buy precsription and OTC medicines, consult doctor online, book doctor appointments, ask free health questions",
    site_doctoroncall: "DoctorOnCall",
    mainpage_search_doc: "Search DoctorOnCall",
    mainpage_search_medicine: "Search Medicine",
    mainpage_searchsuggestion_glucose_control : "Glucose Control",
    mainpage_searchsuggestion_cholestrol_management: "Cholestrol Management",
    mainpage_searchsuggestion_blood_pressure: "Blood Pressure Control",
    mainpage_searchsuggestion_mens_condition: "Men's Condition",
    mainpage_searchsuggestion_birth_control: "Birth Control",
    mainpage_search_history: "Search History",
    mainpage_order_medication: "Order Medicine",
    mainpage_book_appointment: "Book Appointment",
    mainpage_consult_doctor: "Consult A Doctor",
    mainpage_ask_question: "Ask Free Question",
    mainpage_health_articles_days: "days ago",
    mainpage_health_articles_years : "yrs exp",
    mainpage_health_articles_gp: "General Practitioner",
    mainpage_pharma_order_medicine: "Order Medicine Online",
    mainpage_pharma_order_medicine_desc: "100% Genuine medicine, same day delivery. Private consultation with a registered doctor",
    mainpage_pharma_medicine: "Medicines",
    mainpage_pharma_wellness_lifestyle: "Wellness",
    mainpage_pharma_personal_care: "Personal Care",
    mainpage_pharma_lipitor_tablet: "Lipitor 20mg Tablet", 
    mainpage_pharma_price_RM42: "RM 42.00",
    mainpage_pharma_add_to_cart: "Add to Cart",
    mainpage_pharma_crestor_tablet: "Crestor 10mg Tablet",
    mainpage_pharma_price_RM112: "RM 112.00",
    mainpage_plavix_tablet: "Plavix 75mg Tablet",
    mainpage_pharma_price_RM105: "RM 105.00",
    mainpage_pharma_norvasc_tablet: "Norvasc 5mg Tablet",
    mainpage_pharma_price_RM18: "RM 18.00",
    mainpage_pharma_aspirin: "Aspirin Cardio 100mg",
    mainpage_pharma_price_RM3_9: "RM 3.90 ",
    mainpage_pharma_flavette_tablet: "Flavettes Effervescent <br>Glow Tablet",
    mainpage_pharma_price_RM55: "RM 55.00",
    mainpage_pharma_rate_4_8: "(4.8)",
    mainpage_pharma_blackmore_vitamin: "Blackmores Buffered <br>Vitamin C",
    mainpage_pharma_rate_4_7: "(4.7)",
    mainpage_pharma_price_RM43_02: "RM 43.02",
    mainpage_pharma_neurobion: "Neurobion 10’s",
    mainpage_pharma_price_RM13_8: "RM 13.80",
    mainpage_pharma_berocca_tablet: "Berocca Effervescent <br>Tablet",
    mainpage_pharma_price_RM61_6: "RM 61.60",
    mainpage_pharma_blackmore_mineral_tablet: "Blackmores Multivitamins <br>+ Minerals Tablet",
    mainpage_pharma_price_RM32_8: "RM 32.80",
    mainpage_pharma_alpecin_shampoo: "Alpecin Caffeine Hybrid Shampoo",
    mainpage_pharma_price_RM34: "RM 34.00",
    mainpage_pharma_audace_tonic: "Audace Hair Tonic",
    mainpage_pharma_rate_4_5: "(4.5)",
    mainpage_pharma_price_RM47_92: "RM 47.92",
    mainpage_pharma_ripded_lotion: "Ridped Lotion",
    mainpage_pharma_rate_4_4: "(4.4)",
    mainpage_pharma_price_RM12: "RM 12.00",
    mainpage_pharma_selsun_suspension: "Selsun 2.5% Suspension",
    mainpage_pharma_price_RM43_70: "RM 43.70",
    mainpage_pharma_pantene_shampoo: "Pantene Hair Fall Shampoo",
    mainpage_pharma_price_RM15_90: "RM 15.90",
    mainpage_consult_doctor_online: "Consult Doctor Online",
    mainpage_consult_doctor_desc: "Connect to Malaysian Medical Council registered doctors and get the care you need in 3 simple steps",
    mainpage_consultdoc_step1: "1",
    mainpage_consultdoc_signup: "Sign up</a> or Log In <br> to DoctorOnCall",
    mainpage_consultdoc_step2: "2",
    mainpage_consultdoc_speak_with_doc: "Speak with a doctor and receive<br> treatment and answers",
    mainpage_consultdoc_step3: "3",
    mainpage_consultdoc_receive_med: "Receive your medication- <br> delivered to your doorstep!",
    mainpage_book_doctor_appointment: "Book Doctor Appointment",
    mainpage_book_doctor_appointment_desc: "Book your medical specialist appointment across Malaysia's trusted clinic & hospital chains",
    mainpage_bookdoc_pediatrician: "Pediatrician",
    mainpage_bookdoc_orthopaedic: "Orthopaedic",
    mainpage_bookdoc_obstetrician_gynecologist: "Obstetrician & Gynecologist",
    mainpage_bookdoc_cardiologist: "Cardiologist",
    mainpage_bookdoc_ear_nose_throat_specialist: "Ear Nose Throat Specialist",
    mainpage_bookdoc_dermatologist: "Dermatologist",
    mainpage_health_article: "Health Articles",
    mainpage_health_article_desc: "Expand your health knowledge immediately with answers from registered doctors",
    mainpage_category_general_health: "General Health",
    mainpage_category_mens_health: "Men's Health",
    mainpage_category_womens_health: "Women's Health",
    mainpage_category_sexual_health: "Sexual Health",
    mainpage_category_eye_condition: "Eye Condition",
    mainpage_category_sore_throat: "Sore Throat",
    mainpage_category_migraine: "Migraine",
    mainpage_category_minor_injury: "Minor Injuries",
    mainpage_category_fatty_liver: "Fatty Liver",
    mainpage_category_cough_cold: "Cough & Cold",
    mainpage_category_dengue: "Dengue",
    mainpage_category_constipation: "Constipation",
    mainpage_category_skin_condition: "Skin Condition",
    mainpage_category_asthma: "Asthma",
    mainpage_category_acid_reflux: "Acid Reflux",
    mainpage_category_erectile_dysfunction: "Erectile Dysfunction",
    mainpage_category_premature_ejaculation: "Premature Ejaculation",
    mainpage_category_vaginal_discharge: "Vaginal Discharge",
    mainpage_category_missed_period: "Missed Period",
    mainpage_category_uti: "UTI",
    mainpage_category_irregular_period: "Irregular Period",
    mainpage_category_birth_control: "Birth Control",
    mainpage_category_syphilis: "Syphilis",
    mainpage_category_hiv: "HIV",
    mainpage_category_herpes: "Herpes",
    mainpage_category_gonorrhea: "Gonorrhea",
    mainpage_ask_doctor: "Ask Doctors",
    mainpage_ask_doctor_desc: "Ask your health questions anonymously and get answers from a qualified doctor within minutes",
    mainpage_askdoc_kencing_manis: "Kencing Manis",
    mainpage_askdoc_kencing_manis_question: "Sometimes I feel my tummy keeps on contracting once in a while but I can still feel the baby’s movement. Should I visit my doctor?",
    mainpage_askdoc_dr_sashini: "Dr Sashini",
    mainpage_askdoc_general_practitioner: "General Practitioner",
    mainpage_askdoc_mati_pucuk: "Mati Pucuk",
    mainpage_askdoc_mati_pucuk_question: "Bagaimana Slidenafil Ubat Viagra<br> Berkesan Dan Cara Pengunaan",
    mainpage_askdoc_keputihan: "Keputihan",
    mainpage_askdoc_keputihan_desc: "Penyebab, Diagnosis, Pengubatan Dan Pencegahan Penyakit Keputihan",
    mainpage_askdoc_vaginosis: "Vaginosis",
    mainpage_askdoc_vaginosis_question: "Apakah penyakit Vaginosis bakteria dan rawatannya?",
    mainpage_askdoc_urti: "URTI",
    mainpage_askdoc_urti_question: "Apakah URTI Dan Cara Mengelakkan Jangkitan?",
    mainpage_askdoc_haid_sakit: "Haid Sakit",
    mainpage_askdoc_haid_sakit_question: "Apakah senggugut dan bagaimana mencegah dan merawat?",
    mainpage_askdoc_vulvitis: "Vulvitis",
    mainpage_askdoc_vulvitis_question: "Apakah penyakit Vulvitis dan rawatan sesuai?",
    mainpage_askdoc_penyakit_kelamin: "Penyakit Kelamin",
    mainpage_askdoc_penyakit_kelamin_question: "Penyebab, Gejala, Diagnosis Dan Ubat Sesuai Untuk Penyakit Kelamin",
    mainpage_next_page: "Next Page",
    mainpage_connect_doctor_instant: "Connect With A Doctor Instantly",
    mainpage_connect_doctor_desc: "Call, chat or have a video call privately with a MMC registered doctor",
    mainpage_connect_doctor: "Connect With A Doctor",
    mainpage_featured_on: "Featured On",
    mainpage_subscribe_health_insight: "Subscribe to our Free Health Insights",
    mainpage_subscribe_desc: "Get notified about new health articles, and any new offers and new promotions. You can unsubscribe at any time. ",
    mainpage_subscribe: "Subscribe", 
    tanya: "/tanya/en"
    },
    
    

  bm: {
    cart_item_added:"Dimasukan ke Troli", //TODO - translate
    header_order_medicine: "Beli Ubat",
    header_book_appointment: "Buat Temu Janji",
    header_consult_doctor: "Konsultasi bersama Doktor",
    header_more: "Lebih Lanjut",
    header_about_us: "Tentang Kami",
    header_ask_question: "Tanya Soalan",
    header_read_article: "Baca Artikel Kesihatan",
    header_faq: "FAQ",
    header_media: "Media",
    header_careers: "Kerjaya",
    header_panel_doctors: "Panel Doktor",
    header_corporate_partnerships: "Rakan Kongsi Korporat",
    header_contact_us: "Hubungi Kami",
    header_bm_eng: "BM / ENG",
    header_bm:"Bahasa",
    header_en:"English",
    header_button_signuplogin: "Daftar / Log Masuk",
    footer_aboutdesc: "DoctorOnCall adalah platform konsultasi Doktor atas talian pertama & terbesar di Malaysia. Kami menyediakan perkhidmatan kesihatan melalui servis mesej, panggilan video & panggilan telefon.",
    footer_button_readmore: "Baca Lebih Lanjut ",
    footer_services: "Perkhidmatan Kami",
    footer_order_medicine: "Beli Ubat",
    footer_consult_doctor: "Konsultasi bersama Doktor",
    footer_ask_question: "Tanya Soalan",
    footer_read_article: "Baca Artikel Kesihatan",
    footer_search_hospitals: "Cari Hospital",
    footer_search_doctors: "Cari Doktor",
    footer_book_appointment: "Buat Temu Janji",
    footer_tanya_doktor: "Tanya Doktor (Soalan)",
    footer_doctoroncall: "DoctorOnCall",
    footer_about_us: "Tentang Kami",
    footer_privacy: "Privasi",
    footer_faq: "FAQ",
    footer_contact_us: "Hubungi Kami",
    footer_terms_of_use: "Terma Penggunaan",
    footer_doctors_login: "Log Masuk Doktor",
    footer_media: "Media",
    footer_reach_us: "Hubungi Kami",
    footer_social: "Sosial",
    footer_maps: "Peta",
    footer_english: "English",
    footer_bahasa: "Bahasa",
    footer_health_centre: "Pusat Kesihatan",
    footer_en_mens_health: "Men's Health",
    footer_en_womens_health: "Women's Health",
    footer_en_general_health: "General Health",
    footer_en_sexual_health: "Sexual Health",
    footer_bm_mens_health: "Kesihatan Lelaki",
    footer_bm_womens_health: "Kesihatan Wanita",
    footer_bm_general_health: "Kesihatan Umum",
    footer_bm_sexual_health: "Kesihatan Seksual",
    footer_hipertensi: "Hipertensi",
    footer_hipotensi: "Hipotensi",
    footer_hiv_aids: "HIV dan AIDS",
    footer_sinusitis: "Sinusitis",
    footer_menstruasi: "Menstruasi",
    footer_buasir: "Buasir",
    footer_asma: "Asma",
    footer_diabetes: "Diabetes",
    footer_migrain: "Migrain",
    footer_klamidia: "Klamidia",
    footer_vaginosis_bakteria: "Vaginosis bakteria",
    footer_vulvitis: "Vulvitis",
    footer_herpes_zoster: "Herpes zoster",
    footer_HPV: "HPV",
    footer_kutu: "Kutu",
    footer_haid_: "Haid-sakit",
    footer_viagra: "Viagra",
    footer_vaginitis: "Vaginitis",
    footer_prediabetes: "Prediabetes",
    footer_hipertensi_pulmonal: "Hypertensi pulmonal",
    footer_disfungsi_seksual: "Disfungsi seksual",
    footer_herpes_genital: "Herpes genital (herpes simplex)",
    footer_kolestrol_tinggi: "Kolestrol tinggi",
    footer_strok: "Strok",
    footer_hepatitisB: "Hepatitis B",
    footer_jenis1_diabetes: "Jenis 1 Diabetes",
    footer_psoriasis: "Psoriasis",
    footer_gallstones: "Gallstones",
    footer_ejakulasi_pramatang: "Ejakulasi pramatang",
    footer_sifilis: "Sifilis",
    footer_gonore: "Gonore",
    footer_hepatitsA: "Hepatitis A",
    footer_jenis2_diabetes: "Diabetes Jenis 2",
    footer_hepatitisC: "Hepatitis C",
    footer_impotensi: "Impotensi",
    footer_diabetes_insipidus: "Diabetes insipidus",
    footer_kandidiasis: "Kandidiasis - Pengenalan",
    footer_penyakit_kelamin: "Penyakit Kelamin - Pengenalan",
    footer_sakit_tekak: "Sakit tekak - single",
    footer_ketuat: "Ketuat",
    footer_tiroid: "Tiroid - Pengenalan",
    footer_tonsil: "Tonsil - pengenalan",
    mainpage_shop_by_category: "Beli Mengikut Kategori",
    mainpage_medicine_drug: "Ubat dan Preskripsi Ubat",
    mainpage_nutrition_vitamin_supplement: "Nutrisi, Vitamin & Suplemen",
    mainpage_personal_care: "Peribadi",
    mainpage_deliver_doorstep: "Kami menghantar sehingga ke pintu rumah anda",
    mainpage_free_of_charge: "Secara Percuma",
    mainpage_order_now: "Dapatkan Ubat Segera",
    mainpage_consult_doctor_now: "Hubungi Doktor Sekarang",
    mainpage_appointment_now: "Atur Temujanji Sekarang",
    mainpage_read_health: "Baca Artikel Kesihatan Sekarang",
    mainpage_ask_doctor_now: "Tanya Doktor Sekarang",
    category_quick_filter: "Tapisan Ringkas",
    product_advise: "Anda dinasihatkan untuk berunding dengan pakar perubatan sebelum mengambil produk ini",
    product_img_disclaimer:"The product images shown are for illustration purposes only and may not be an exact representation of the product",     //TODO: translate
    product_prescription_required: "Preskripsi Diperlukan",
    product_discount: "-20%",
    product_RM: "RM ",
    product_out_of_stock: "Kehabisan Stok",
    product_manufactured_by: "Dikilangkan oleh",
    product_supplied_buy: "Dibekalkan oleh",
    product_active_ingredient: "Bahan Aktif",
    product_packaging: "Pembungkusan",
    product_quantity: "Kuantiti",
    product_add_to_cart: "Masukkan ke Troli",
    product_check_out: "Semak Keluar", // Check Out // Still not sure //TODO
    product_not_in_stock: "Tiada Dalam Stok",
    product_about_medicine: "Tentang Ubat",
    product_description_of: "Penerangan tentang ",
    product_usage: "Penggunaan",
    product_how_to_take: "Cara Pengambilan",
    product_dosage_composition: "Sukatan dan Komposisi",
    product_dosage_composition_of: "Sukatan dan Komposisi untuk ",
    product_professional_opinion: "Nasihat Pakar",
    product_professional_opinion_of: "Nasihat Pakar mengenai ",
    product_precautionary_steps: "Langkah berjaga-jaga",
    product_precautionary_steps_of: "Langkah berjaga-jaga bagi ",
    product_side_effects: "Kesan Sampingan",
    product_side_effects_of: "Kesan Sampingan bagi ",
    product_frequently_ask_questions: "Soalan yang Kerap Ditanya",
    product_frequently_ask_questions_of: "Soalan yang Kerap Ditanya mengenai ",
    product_information_updated: "Maklumat dikemas kini pada: ",
    product_disclaimer: "Penafian",
    product_disclaimer_desc: "Kandungan laman web ini adalah bertujuan untuk memberi maklumat sahaja, bagi kegunaan para pengamal perubatan dan bukan bertujuan sebagai rujukan kepada pengguna untuk membuat sebarang pembelian atau menggantikan nasihat seorang pengamal perubatan. Keberkesanan dan kesan sampingan ubat-ubatan mungkin berbeza dari seorang pengguna dengan pengguna yang lain. Kami tidak menyarankan pengguna untuk membuat diagnosis atau rawatan sendiri. Pesakit haruslah sentiasa mendapatkan nasihat daripada doktor atau ahli farmasi bertauliah sebelum mengambil atau menggunakan sebarang ubat-ubatan. Isi kandungan laman web ini adalah terhad dan mungkin tidak merangkumi semua aspek tentang ubat-ubatan yang berkenaan. Perkhidmatan kami hanya bertujuan untuk menyokong dinamik antara doktor dan pesakit bukan menggantikannya. <br><br> Pemberian ubat-ubatan yang memerlukan preskripsi adalah tertakluk kepada penelitian kami terhadap preskripsi yang dikeluarkan oleh doktor yang berdaftar di bawah Majlis Perubatan Malaysia (MPM). Jika perlu, kami akan menyediakan perkhidmatan tele-konsultasi dengan salah seorang doktor panel kami yang berdaftar. Ini bukanlah iklan berkenaan ubat kerana iklan sedemikian memerlukan kebenaran dari Lembaga Iklan Ubat Malaysia.",
    product_available_area: "boleh didapati di banyak tempat di Malaysia. Kuala Lumpur, Bukit Bintang, Titiwangsa, Setiawangsa, Wangsa Maju, Kepong, Segambut, Bandar Tun Razak, Cheras, Subang Jaya, Petaling Jaya, Mont Kiara, Puchong, Bandar Sunway, TTDI, Seri Kembangan, Klang, Bukit Tinggi, Damansara, Sentul, Penang, George Town, Jelutong, Gelugor, Bayan Baru, Bandar Baru Air Itam, Sungai Ara, Bukit Mertajam, Butterworth, Perai, Johor Bahru, Skudai, Bukit Indah, Gelang Patah, Senai, Pasir Gudang, Taman Daya, Taman Molek, Taman Perling, Tebrau, Danga Bay, Larkin, Nusajaya, Pontian, Masai, Setia Tropika, Desaru, Tampoi. ",
    product_see_more: "Lihat Lagi",
    product_see_less: "Lihat Sedikit",
    product_unsure_medicine: "Kurang pasti dengan ubat anda?",
    product_get_help: "Minta bantuan daripada doktor bertauliah",
    product_consult_doctor: "Bercakap dengan Doktor",
    product_related_health_article: "Artikel Kesihatan Berkaitan",
    seo_product_title:"- Kegunaan, Dosage, Side Effects,Price, Benefits - DoctorOnCall", //TODO
    seo_main_title:"Farmasi Online Malaysia | Beli Ubat, Tanya Doktor Online", 
    seo_meta_desc:"Beli ubat preskripsi & OTC dari farmasi online DoctorOnCall. Buat temujanji dengan doktor & hospital, tanya doktor soalan secara percuma,Dapat 20% diskaunt & penghantaran ubat percuma ",
    seo_meta_keyword: "Farmasi online, beli ubat preskripsi dan OTC, tanya doktor online, temujanji pakar & doktor, tanya doktor soalan percuma",
    site_doctoroncall: "DoctorOnCall",
    mainpage_search_doc: "Carian DoctorOnCall",
    mainpage_search_medicine: "Carian Ubat",
    mainpage_searchsuggestion_glucose_control : "Glucose Control",
    mainpage_searchsuggestion_cholestrol_management: "Cholestrol Management",
    mainpage_searchsuggestion_blood_pressure: "Blood Pressure Control",
    mainpage_searchsuggestion_mens_condition: "Men's Condition",
    mainpage_searchsuggestion_birth_control: "Birth Control",
    mainpage_search_history: "Search History",
    mainpage_order_medication: "Farmasi Online", //Pembelian Ubat ubatan
    mainpage_book_appointment: "Temujanji Doktor", //Buat Temujanji
    mainpage_consult_doctor: "Hubungi Doktor", //Bercakap dengan Doktot
    mainpage_ask_question: "Tanya Doktor", //Tanya Soalan Percuma
    mainpage_health_articles_days: "hari lalu",
    mainpage_health_articles_years : "tahun pengalaman",
    mainpage_health_articles_gp: "Doktor Perubatan Am",
    mainpage_pharma_order_medicine: "Farmasi Online", //Beli Ubat Secara Online
    mainpage_pharma_order_medicine_desc: "100% Ubat-Ubatan Tulen, penghantaran pada hari yang sama. Konsultasi dengan doktor berdaftar secara peribadi",
    mainpage_pharma_medicine: "Ubat",
    mainpage_pharma_wellness_lifestyle: "Kesihatan",
    mainpage_pharma_personal_care: "Peribadi",
    mainpage_pharma_lipitor_tablet: "Lipitor 20mg Tablet", 
    mainpage_pharma_price_RM42: "RM 42.00",
    mainpage_pharma_add_to_cart: "Beli Sekarang",
    mainpage_pharma_crestor_tablet: "Crestor 10mg Tablet",
    mainpage_pharma_price_RM112: "RM 112.00",
    mainpage_plavix_tablet: "Plavix 75mg Tablet",
    mainpage_pharma_price_RM105: "RM 105.00",
    mainpage_pharma_norvasc_tablet: "Norvasc 5mg Tablet",
    mainpage_pharma_price_RM18: "RM 18.00",
    mainpage_pharma_aspirin: "Aspirin Cardio 100mg",
    mainpage_pharma_price_RM3_9: "RM 3.90 ",
    mainpage_pharma_flavette_tablet: "Flavettes Effervescent <br>Glow Tablet",
    mainpage_pharma_price_RM55: "RM 55.00",
    mainpage_pharma_rate_4_8: "(4.8)",
    mainpage_pharma_blackmore_vitamin: "Blackmores Buffered <br>Vitamin C",
    mainpage_pharma_rate_4_7: "(4.7)",
    mainpage_pharma_price_RM43_02: "RM 43.02",
    mainpage_pharma_neurobion: "Neurobion 10’s",
    mainpage_pharma_price_RM13_8: "RM 13.80",
    mainpage_pharma_berocca_tablet: "Berocca Effervescent <br>Tablet",
    mainpage_pharma_price_RM61_6: "RM 61.60",
    mainpage_pharma_blackmore_mineral_tablet: "Blackmores Multivitamins <br>+ Minerals Tablet",
    mainpage_pharma_price_RM32_8: "RM 32.80",
    mainpage_pharma_alpecin_shampoo: "Alpecin Caffeine Hybrid Shampoo",
    mainpage_pharma_price_RM34: "RM 34.00",
    mainpage_pharma_audace_tonic: "Audace Hair Tonic",
    mainpage_pharma_rate_4_5: "(4.5)",
    mainpage_pharma_price_RM47_92: "RM 47.92",
    mainpage_pharma_ripded_lotion: "Ridped Lotion",
    mainpage_pharma_rate_4_4: "(4.4)",
    mainpage_pharma_price_RM12: "RM 12.00",
    mainpage_pharma_selsun_suspension: "Selsun 2.5% Suspension",
    mainpage_pharma_price_RM43_70: "RM 43.70",
    mainpage_pharma_pantene_shampoo: "Pantene Hair Fall Shampoo",
    mainpage_pharma_price_RM15_90: "RM 15.90",
    mainpage_consult_doctor_online: "Konsultasi Doktor Secara Online", //Bercakap dengan Doktor Secara Online
    mainpage_consult_doctor_desc: "Berhubung dengan doktor yang berdaftar dengan Majlis Perubatan Malaysia dan dapatkan perkhidmatan yang anda inginkan melalui 3 langkah mudah",
    mainpage_consultdoc_step1: "1",
    mainpage_consultdoc_signup: "Daftar </a> atau Log Masuk<br> ke DoctorOnCall",
    mainpage_consultdoc_step2: "2",
    mainpage_consultdoc_speak_with_doc: "Bercakap dengan doktor dan dapatkan <br> rawatan dan jawapan kepada masalah anda",
    mainpage_consultdoc_step3: "3",
    mainpage_consultdoc_receive_med: "Dapatkan Ubat-Ubatan Anda - <br>Dihantar terus ke rumah! ",
    mainpage_book_doctor_appointment: "Buat temujanji dengan doktor",
    mainpage_book_doctor_appointment_desc: "Buat temujanji dengan pakar seluruh Malaysia dari pelbagai cawangan klinik dan hospital",
    mainpage_bookdoc_pediatrician: "Pakar Kanak-Kanak",
    mainpage_bookdoc_orthopaedic: "Pakar Tulang",
    mainpage_bookdoc_obstetrician_gynecologist: "Pakar Kesihatan Wanita",
    mainpage_bookdoc_cardiologist: "Pakar Jantung",
    mainpage_bookdoc_ear_nose_throat_specialist: "Pakar Telinga Hidung & Tekak",
    mainpage_bookdoc_dermatologist: "Pakar Kulit",
    mainpage_health_article: "Artikel Kesihatan",
    mainpage_health_article_desc: "Tambah info kesihatan anda secara pantas dengan jawapan daripada doktor berdaftar",
    mainpage_category_general_health: "Kesihatan Am",
    mainpage_category_mens_health: "Kesihatan Lelaki",
    mainpage_category_womens_health: "Kesihatan Wanita",
    mainpage_category_sexual_health: "Kesihatan Seksual",
    mainpage_category_eye_condition: "Sakit Mata",
    mainpage_category_sore_throat: "Sakit Tekak",
    mainpage_category_migraine: "Migrain",
    mainpage_category_minor_injury: "Kecederaan kecil",
    mainpage_category_fatty_liver: "Penyakit Hati",
    mainpage_category_cough_cold: "Batuk Selsema",
    mainpage_category_dengue: "Denggi",
    mainpage_category_constipation: "Sembelit",
    mainpage_category_skin_condition: "Masalah Kulit",
    mainpage_category_asthma: "Asma",
    mainpage_category_acid_reflux: "Asid Refluks",
    mainpage_category_erectile_dysfunction: "Mati Pucuk",
    mainpage_category_premature_ejaculation: "Ejakulasi Pramatang",
    mainpage_category_vaginal_discharge: "Keputihan",
    mainpage_category_missed_period: "Haid Lewat",
    mainpage_category_uti: "Kencing Kotor",
    mainpage_category_irregular_period: "Haid Tidak Teratur",
    mainpage_category_birth_control: "Perancangan Keluarga",
    mainpage_category_syphilis: "Sifilis",
    mainpage_category_hiv: "HIV",
    mainpage_category_herpes: "Herpes",
    mainpage_category_gonorrhea: "Gonorea",
    mainpage_ask_doctor: "Tanya Doktor",
    mainpage_ask_doctor_desc: "Tanya soalan tentang kesihatan secara sulit dan dapatkan jawapan daripada doktor berdaftar dengan segera",
    mainpage_askdoc_kencing_manis: "Kencing Manis",
    mainpage_askdoc_kencing_manis_question: "Sometimes I feel my tummy keeps on contracting once in a while but I can still feel the baby’s movement. Should I visit my doctor?",
    mainpage_askdoc_dr_sashini: "Dr Sashini",
    mainpage_askdoc_general_practitioner: "General Practitioner",
    mainpage_askdoc_mati_pucuk: "Mati Pucuk",
    mainpage_askdoc_mati_pucuk_question: "Bagaimana Slidenafil Ubat Viagra<br> Berkesan Dan Cara Pengunaan",
    mainpage_askdoc_keputihan: "Keputihan",
    mainpage_askdoc_keputihan_desc: "Penyebab, Diagnosis, Pengubatan Dan Pencegahan Penyakit Keputihan",
    mainpage_askdoc_vaginosis: "Vaginosis",
    mainpage_askdoc_vaginosis_question: "Apakah penyakit Vaginosis bakteria dan rawatannya?",
    mainpage_askdoc_urti: "URTI",
    mainpage_askdoc_urti_question: "Apakah URTI Dan Cara Mengelakkan Jangkitan?",
    mainpage_askdoc_haid_sakit: "Haid Sakit",
    mainpage_askdoc_haid_sakit_question: "Apakah senggugut dan bagaimana mencegah dan merawat?",
    mainpage_askdoc_vulvitis: "Vulvitis",
    mainpage_askdoc_vulvitis_question: "Apakah penyakit Vulvitis dan rawatan sesuai?",
    mainpage_askdoc_penyakit_kelamin: "Penyakit Kelamin",
    mainpage_askdoc_penyakit_kelamin_question: "Penyebab, Gejala, Diagnosis Dan Ubat Sesuai Untuk Penyakit Kelamin",
    mainpage_next_page: "Halaman Seterusnya",
    mainpage_connect_doctor_instant: "Hubungi doktor dengan segera", //Berhubung dengan doktor dalam masa yang singkat
    mainpage_connect_doctor_desc: "Buat panggilan telefon, video atau chat dengan doktor yang berdaftar di bawah MPM", //Berhubung dengan doktor berdaftar MPM melalui audio, chat atau video
    mainpage_connect_doctor: "Hubungi doktor", //Berhubung dengan seorang doktor
    mainpage_featured_on: "Seperti yang terpapar di",
    mainpage_subscribe_health_insight: "Langgan info kesihatan secara percuma",
    mainpage_subscribe_desc: "Dapatkan pemberitahun tentang artikel, tawaran dan promosi terbaru kami. Anda boleh berhenti melanggan pada bila-bila masa. ",
    mainpage_subscribe: "Langgan", 
    tanya: "/tanya"
  }
};

module.exports = library;